package cadastros;

import conexao.clsFunctions;
import ferramentas.clsFerramentaChamado;
import ferramentas.clsValidacao;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frmAbrirChamado extends javax.swing.JFrame {

    /** Creates new form frmCadTurno */
    public frmAbrirChamado() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optStatus = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblChamado = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JEditorPane();
        txtChamado = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtData = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        cboFunc = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cboEmpr = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btnSair2 = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Abrir Chamado");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setName("frmCadTurno"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblChamado.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tblChamado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChamado.setName("tblChamado"); // NOI18N
        tblChamado.setUpdateSelectionOnSort(false);
        jScrollPane2.setViewportView(tblChamado);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 357, 142));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 359, -1, 10));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chamado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Número do Chamado");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Descrição do Problema");

        txtDescricao.setPreferredSize(new java.awt.Dimension(250, 20));
        txtDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescricaoKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtDescricao);

        txtChamado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtChamado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtChamadoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtChamadoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtChamado, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(txtChamado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 360, 180));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados da abertura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Empresa");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Data");

        cboFunc.setFont(new java.awt.Font("Arial", 0, 11));
        cboFunc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Funcionário");

        cboEmpr.setFont(new java.awt.Font("Arial", 0, 11));
        cboEmpr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(cboEmpr, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(cboFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboEmpr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 360, 130));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 11, 10, 460));

        btnSair2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_sair.png"))); // NOI18N
        btnSair2.setToolTipText("Sair");
        btnSair2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSair2MouseClicked(evt);
            }
        });
        btnSair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 30, 30));

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_pesquisar.png"))); // NOI18N
        btnPesquisar.setToolTipText("Pesquisa");
        btnPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseClicked(evt);
            }
        });
        getContentPane().add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 151, 30, 30));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_salvar.png"))); // NOI18N
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 81, 30, 30));

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_excluir.png"))); // NOI18N
        btnExcluir.setToolTipText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 116, 30, 30));

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_alterar.png"))); // NOI18N
        btnAlterar.setToolTipText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarMouseClicked(evt);
            }
        });
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 46, 30, 30));

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_novo.png"))); // NOI18N
        btnNovo.setToolTipText("Novo");
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoMouseClicked(evt);
            }
        });
        getContentPane().add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 11, 30, 30));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-444)/2, (screenSize.height-520)/2, 444, 520);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        /*Para usar a classe de funções é necessário adicionar uma Exceção, para que se der alguma erro
         * o mesmo possa ser tratado.
         * Como não é possível alterar a linha que declara este método foi necessário inserir o função Try Catch
         */

        try {
            clsFunctions function = new clsFunctions();
            clsAbrirChamadoDAO cadChamadoDAO = new clsAbrirChamadoDAO();

            txtChamado.setText(Integer.toString(function.ProxRegistro("CC_CAD_CHAMADO", "ID_CHAMADO")));

            clsFerramentaChamado fChamado = new clsFerramentaChamado();
            fChamado.HabilitaNovo(txtChamado, txtData, txtDescricao, cboFunc, cboEmpr, btnAlterar, btnSalvar);

            function.carregaCombo(cadChamadoDAO.ListaComboEmpresa(), cboEmpr, "EMPRESA");
            function.carregaCombo(cadChamadoDAO.ListaComboFuncionario(), cboFunc, "FUNCIONARIO");

            function.carregaTabela(cadChamadoDAO.ListaChamado(), tblChamado); //carrega a tabela de turno ao abrir tela

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    "Ocorreram problemas ao abrir tela.\n(" + err.getMessage() + ")", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_formWindowOpened

    private void btnSair2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSair2MouseClicked
}//GEN-LAST:event_btnSair2MouseClicked

    private void btnSair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_btnSair2ActionPerformed

    private void btnPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseClicked
        // TODO add your handling code here:
        try {

            clsFerramentaChamado fChamado = new clsFerramentaChamado();

            fChamado.LimparChamado(txtChamado, txtData, txtDescricao, cboFunc, cboEmpr);

            fChamado.HabilitaPesquisa(txtChamado, txtData, txtDescricao, cboFunc, cboEmpr, btnAlterar, btnSalvar);

            btnAlterar.setEnabled(true);

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    err.getMessage(), "Atenção!", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_btnPesquisarMouseClicked

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked

        // TODO add your handling code here:

        if (btnSalvar.isEnabled() != false) {
            if (txtData.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Escolha uma data!!",
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);

            } else if (cboEmpr.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Escolha a empresa!",
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);

            } else if (cboFunc.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Escolha o funcionário!",
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);

            } else {

                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String sData = sdf.format(txtData.getDate()); // pego e transformo a data no padrão acima

                String sEmpresa, sFunc;
                int iCodEmpr, iCodFunc, end;

                sEmpresa = (String) cboEmpr.getSelectedItem();
                end = sEmpresa.indexOf(" ");

                if (end == -1) {
                    iCodEmpr = Integer.parseInt(sEmpresa);
                } else {
                    iCodEmpr = Integer.parseInt(sEmpresa.substring(0, end));
                }
                sFunc = (String) cboFunc.getSelectedItem();
                end = sFunc.indexOf(" ");

                if (end == -1) {
                    iCodFunc = Integer.parseInt(sFunc);
                } else {
                    iCodFunc = Integer.parseInt(sFunc.substring(0, end));
                }

                try {

                    clsAbrirChamado CadChamado = new clsAbrirChamado(Integer.parseInt(txtChamado.getText()),
                            txtDescricao.getText(), sData, iCodFunc, iCodEmpr);

                    clsAbrirChamadoDAO CadChamadoDAO = new clsAbrirChamadoDAO();

                    CadChamadoDAO.InserirChamado(CadChamado);

                    clsFerramentaChamado fChamado = new clsFerramentaChamado();
                    fChamado.HabilitaNovo(txtChamado, txtData, txtDescricao, cboFunc, cboEmpr, btnAlterar, btnSalvar);

                    clsFunctions function = new clsFunctions();
                    function.carregaTabela(CadChamadoDAO.ListaChamado(), tblChamado);

                } catch (Exception err) {
                    JOptionPane.showMessageDialog(this,
                            "Não foi possível salvar/alterar este registro.\n(" + err.getMessage() + ")", "Atenção!", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
}//GEN-LAST:event_btnSalvarMouseClicked

    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
        // TODO add your handling code here:
        if (btnExcluir.isEnabled() == true) {
            try {
                clsFunctions function = new clsFunctions();
                String sChamado;
                int iChamado;

                clsAbrirChamadoDAO CadChamadoDAO = new clsAbrirChamadoDAO();

                DefaultTableModel tableModel = (DefaultTableModel) tblChamado.getModel();

                int row = tblChamado.getSelectedRow();

                if (row != -1) {//se tiver linha selecionada, exclui da linha

                    sChamado = tableModel.getValueAt(row, 1).toString();
                    CadChamadoDAO.ExcluirChamado(sChamado);

                } else { //senão exclui do campo
                    CadChamadoDAO.ExcluirChamado(txtChamado.getText());
                }

                clsFerramentaChamado fChamado = new clsFerramentaChamado();
                fChamado.LimparChamado(txtChamado, txtData, txtDescricao, cboFunc, cboEmpr);

                function.carregaTabela(CadChamadoDAO.ListaChamado(), tblChamado); //atualiza a tabela de turno ao excluir registro

            } catch (Exception err) {
                JOptionPane.showMessageDialog(this,
                        "Não foi possível realizar Exlusão.\n(" + err.getMessage() + ")", "Atenção!", JOptionPane.ERROR_MESSAGE);
            }
        }
}//GEN-LAST:event_btnExcluirMouseClicked

    private void btnAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseClicked
        // TODO add your handling code here:
        if (btnAlterar.isEnabled() != false) {
            try {
                clsFerramentaChamado fChamado = new clsFerramentaChamado();
                fChamado.HabilitaAlterar(txtChamado, txtData, txtDescricao, cboFunc, cboEmpr, btnAlterar, btnSalvar);
            } catch (SQLException ex) {
                Logger.getLogger(frmCadEstacionamento.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
}//GEN-LAST:event_btnAlterarMouseClicked

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_btnAlterarActionPerformed

    private void btnNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseClicked
        // TODO add your handling code here:

        try {
            clsFerramentaChamado fChamado = new clsFerramentaChamado();
            fChamado.HabilitaNovo(txtChamado, txtData, txtDescricao, cboFunc, cboEmpr, btnAlterar, btnSalvar);
        } catch (SQLException ex) {
            Logger.getLogger(frmCadEstacionamento.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_btnNovoMouseClicked

    private void txtChamadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChamadoKeyPressed
        // TODO add your handling code here:
        try {

            clsAbrirChamadoDAO CadAbrirChamadoDAO = new clsAbrirChamadoDAO();
            clsFunctions function = new clsFunctions();

            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

                ResultSet rst = CadAbrirChamadoDAO.ConsultarChamado(txtChamado.getText());

                if (rst.next()) {

                    txtDescricao.setText(rst.getString("DESCRICAO"));
                    txtData.setDate(rst.getDate("ABERT"));
                    cboEmpr.setSelectedItem(rst.getString("EMPR"));
                    cboFunc.setSelectedItem(rst.getString("FUNC"));

                } else {

                    txtDescricao.setText("");
                    txtData.setDate(null);
                    cboEmpr.setSelectedItem(0);
                    cboFunc.setSelectedItem(0);

                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Funcionario não cadastrado.\n", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
            txtChamado.setText(null);
        }
    }//GEN-LAST:event_txtChamadoKeyPressed

    private void txtChamadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChamadoKeyTyped
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        Valida.TamanhoMax(txtChamado, evt, 4);
        Valida.SomenteNumeros(txtChamado, evt);
    }//GEN-LAST:event_txtChamadoKeyTyped

    private void txtDescricaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoKeyTyped
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        Valida.TamanhoMax(txtDescricao, evt, 255);
    }//GEN-LAST:event_txtDescricaoKeyTyped
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmAbrirChamado().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair2;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cboEmpr;
    private javax.swing.JComboBox cboFunc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.ButtonGroup optStatus;
    private javax.swing.JTable tblChamado;
    private javax.swing.JTextField txtChamado;
    private com.toedter.calendar.JDateChooser txtData;
    private javax.swing.JEditorPane txtDescricao;
    // End of variables declaration//GEN-END:variables
}
