/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmCadEntradaEst.java
 *
 * Created on 09/04/2011, 14:57:20
 */
package cadastros;

import conexao.clsFunctions;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AndreSAG
 */
public class frmCadConsumo extends javax.swing.JFrame {

    /** Creates new form frmCadEntrada */
    public frmCadConsumo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDataConsumo = new javax.swing.JFormattedTextField();
        txtQtdConsumida = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        cboProduto = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblConsumo = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lançamento Consumo");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consumo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel2.setText("Data");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel4.setText("Qtd. Consumida");

        txtDataConsumo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDataConsumoFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel3.setText("Produto");

        cboProduto.setFont(new java.awt.Font("Arial", 0, 11));
        cboProduto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboProdutoMouseClicked(evt);
            }
        });
        cboProduto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboProdutoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQtdConsumida, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDataConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQtdConsumida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 11, 260, 120));

        tblConsumo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tblConsumo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblConsumo.setName("tblConsumo"); // NOI18N
        tblConsumo.setUpdateSelectionOnSort(false);
        jScrollPane2.setViewportView(tblConsumo);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 260, 180));

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_novo.png"))); // NOI18N
        btnNovo.setToolTipText("Novo");
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoMouseClicked(evt);
            }
        });
        getContentPane().add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 11, 10, 310));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_salvar.png"))); // NOI18N
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 30, 30));

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_excluir.png"))); // NOI18N
        btnExcluir.setToolTipText("Excluir");
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, 30, 30));

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_sair.png"))); // NOI18N
        btnSair.setToolTipText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 30, 30));

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_alterar.png"))); // NOI18N
        btnAlterar.setToolTipText("Alterar");
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarMouseClicked(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 30, 30));

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_pesquisar.png"))); // NOI18N
        btnPesquisar.setToolTipText("Pesquisa");
        btnPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseClicked(evt);
            }
        });
        getContentPane().add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 30, 30));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-346)/2, (screenSize.height-367)/2, 346, 367);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseClicked
        // TODO add your handling code here:

        try {
            clsFunctions function = new clsFunctions();

            txtDataConsumo.setText(function.fSysDate());
            cboProduto.setSelectedIndex(0);
            txtQtdConsumida.setText("");

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    err.getMessage(), "Atenção!", JOptionPane.ERROR_MESSAGE);
        }

}//GEN-LAST:event_btnNovoMouseClicked

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked

        // TODO add your handling code here:

        String sProduto;
        int iCodProd, end;

        sProduto = (String) cboProduto.getSelectedItem();

        end = sProduto.indexOf(" ");

        if (end == -1) {

            iCodProd = Integer.parseInt(sProduto);
        } else {

            System.out.println(sProduto.substring(0, end));
            iCodProd = Integer.parseInt(sProduto.substring(0, end));
        }

        try {
            clsFunctions function = new clsFunctions();

            clsCadConsumo CadConsumo = new clsCadConsumo(txtDataConsumo.getText(),
                    iCodProd,
                    Double.valueOf(txtQtdConsumida.getText()).doubleValue());

            clsCadConsumoDAO CadConsDAO = new clsCadConsumoDAO();

            CadConsDAO.InserirConsumo(CadConsumo);

            txtQtdConsumida.setText("");
            txtDataConsumo.setText(function.fSysDate());
            cboProduto.setSelectedIndex(0);

            function.carregaTabela(CadConsDAO.ListaConsumo(), tblConsumo); //atualiza a tabela de empresa ao salvar registro

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    "Não foi possível salvar/alterar este registro.\n", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }


}//GEN-LAST:event_btnSalvarMouseClicked

    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
        // TODO add your handling code here:

        String sProduto;
        int iCodProd, end;

        sProduto = (String) cboProduto.getSelectedItem();

        end = sProduto.indexOf(" ");

        if (end == -1) {
            iCodProd = Integer.parseInt(sProduto);
        } else {
            iCodProd = Integer.parseInt(sProduto.substring(0, end));
        }

        try {

            clsFunctions function = new clsFunctions();

            clsCadConsumoDAO CadConsDAO = new clsCadConsumoDAO();

            //Cria modelo do jTable
            DefaultTableModel tableModel = (DefaultTableModel) tblConsumo.getModel();
            //Pego a linha selecionada
            int row = tblConsumo.getSelectedRow();
            //Se tiver linha selecionada
            if (row != -1) {
                //Pego o ID e a Desc do produto e jogo em sProduto
                sProduto = tableModel.getValueAt(row, 1).toString();
                //Acho o ID
                end = sProduto.indexOf(" ");

                if (end == -1) {
                    iCodProd = Integer.parseInt(sProduto);
                } else {
                    //Pego só o ID
                    iCodProd = Integer.parseInt(sProduto.substring(0, end));
                }
                //Envio a data e o ID para o método excluir o dado
                CadConsDAO.ExcluirConsumo(tableModel.getValueAt(row, 0).toString(), iCodProd);

            } else {
                CadConsDAO.ExcluirConsumo(txtDataConsumo.getText(), iCodProd);
            }

            txtQtdConsumida.setText("");
            txtDataConsumo.setText(function.fSysDate());
            cboProduto.setSelectedIndex(0);

            function.carregaTabela(CadConsDAO.ListaConsumo(), tblConsumo); //atualiza a tabela de empresa ao excluir registro

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    "Não foi possível realizar Exclusão.\n", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_btnExcluirMouseClicked

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
}//GEN-LAST:event_btnSairMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_btnSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            clsFunctions function = new clsFunctions();
            clsCadConsumoDAO CadConsDAO = new clsCadConsumoDAO();

            cboProduto.removeAllItems(); //remove os itens que estão no combo

            function.carregaCombo(CadConsDAO.ListaComboProduto(), cboProduto, "PRODUTO");

            function.carregaTabela(CadConsDAO.ListaConsumo(), tblConsumo); //atualiza a tabela de empresa ao salvar registro

            txtQtdConsumida.setText("");
            txtDataConsumo.setText(function.fSysDate());
            cboProduto.setSelectedIndex(0);

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    "Ocorreram problemas ao abrir tela.\n", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_formWindowOpened

    private void cboProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboProdutoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cboProdutoMouseClicked

    private void cboProdutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboProdutoItemStateChanged
        // TODO add your handling code here:
        try {

            String sProduto;
            int iCodProd, end;

            sProduto = (String) cboProduto.getSelectedItem();

            end = sProduto.indexOf(" ");

            if (end == -1) {
                iCodProd = Integer.parseInt(sProduto);
            } else {
                iCodProd = Integer.parseInt(sProduto.substring(0, end));
            }

            clsCadConsumoDAO CadConsDAO = new clsCadConsumoDAO();
            clsFunctions function = new clsFunctions();

            if (!txtDataConsumo.getText().equals("")) {

                ResultSet rst = CadConsDAO.ConsultarConsumo(txtDataConsumo.getText(), iCodProd);

                if (rst.next()) {
                    txtQtdConsumida.setText(String.valueOf(rst.getDouble("QTD")).toString());
                } else {
                    txtQtdConsumida.setText("");
                }

            }
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_cboProdutoItemStateChanged

    private void txtDataConsumoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataConsumoFocusLost
        // TODO add your handling code here:
        try {

            String sProduto;
            int iCodProd, end;

            sProduto = (String) cboProduto.getSelectedItem();

            end = sProduto.indexOf(" ");

            if (end == -1) {
                iCodProd = Integer.parseInt(sProduto);
            } else {
                iCodProd = Integer.parseInt(sProduto.substring(0, end));
            }

            clsCadConsumoDAO CadConsDAO = new clsCadConsumoDAO();
            clsFunctions function = new clsFunctions();

            if (!txtDataConsumo.getText().equals("")) {

                ResultSet rst = CadConsDAO.ConsultarConsumo(txtDataConsumo.getText(), iCodProd);

                if (rst.next()) {
                    txtQtdConsumida.setText(String.valueOf(rst.getDouble("QTD")).toString());
                } else {
                    txtQtdConsumida.setText("");
                }


            }
        } catch (Exception ex) {
        }

    }//GEN-LAST:event_txtDataConsumoFocusLost

    private void btnAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarMouseClicked

    private void btnPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmCadConsumo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cboProduto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblConsumo;
    private javax.swing.JFormattedTextField txtDataConsumo;
    private javax.swing.JFormattedTextField txtQtdConsumida;
    // End of variables declaration//GEN-END:variables
}
