/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmCadEntradaEst.java
 *
 * Created on 09/04/2011, 14:57:20
 */
package cadastros;

import conexao.clsFunctions;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AndreSAG
 */
public class frmCadEntradaEst extends javax.swing.JFrame {

    /** Creates new form frmCadEntrada */
    public frmCadEntradaEst() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNotaFiscal = new javax.swing.JFormattedTextField();
        txtDataEntrada = new javax.swing.JFormattedTextField();
        txtQtdEntrada = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        cboProduto = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEntEst = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lançamento Entrada");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Entrada", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel2.setText("Data");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel4.setText("Qtd. Entrada");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel8.setText("Nota Fiscal");

        txtNotaFiscal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNotaFiscalKeyPressed(evt);
            }
        });

        txtDataEntrada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDataEntradaFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel3.setText("Produto");

        cboProduto.setFont(new java.awt.Font("Arial", 0, 11));
        cboProduto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboProdutoMouseClicked(evt);
            }
        });
        cboProduto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboProdutoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQtdEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQtdEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 11, 310, 150));

        tblEntEst.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tblEntEst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEntEst.setName("tblEntEst"); // NOI18N
        tblEntEst.setUpdateSelectionOnSort(false);
        jScrollPane2.setViewportView(tblEntEst);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 310, 180));

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_novo.jpg"))); // NOI18N
        btnNovo.setToolTipText("Novo");
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoMouseClicked(evt);
            }
        });
        getContentPane().add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 30, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 11, 10, 340));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_salvar.jpg"))); // NOI18N
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, 30, 30));

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_excluir.jpg"))); // NOI18N
        btnExcluir.setToolTipText("Excluir");
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 91, 30, 30));

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_sair.jpg"))); // NOI18N
        btnSair.setToolTipText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 30, 30));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-394)/2, (screenSize.height-397)/2, 394, 397);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseClicked
        // TODO add your handling code here:

        try {
            clsFunctions function = new clsFunctions();

            txtDataEntrada.setText(function.fSysDate());
            cboProduto.setSelectedIndex(0);
            txtNotaFiscal.setText("");
            txtQtdEntrada.setText("");

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    err.getMessage(), "Atenção!", JOptionPane.ERROR_MESSAGE);
        }

}//GEN-LAST:event_btnNovoMouseClicked

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked

        // TODO add your handling code here:

        String sProduto;
        int iCodProd, end;

        sProduto = (String) cboProduto.getSelectedItem();

        end = sProduto.indexOf(" ");

        if (end == -1) {

            iCodProd = Integer.parseInt(sProduto);
        } else {

            System.out.println(sProduto.substring(0, end));
            iCodProd = Integer.parseInt(sProduto.substring(0, end));
        }

        try {
            clsFunctions function = new clsFunctions();

            clsCadEntradaEst CadEntrada = new clsCadEntradaEst(txtNotaFiscal.getText(),
                    txtDataEntrada.getText(), iCodProd, Double.valueOf(txtQtdEntrada.getText()).doubleValue());

            clsCadEntradaEstDAO CadEntDAO = new clsCadEntradaEstDAO();

            CadEntDAO.InserirEntrada(CadEntrada);

            txtNotaFiscal.setText("");
            txtQtdEntrada.setText("");
            txtDataEntrada.setText(function.fSysDate());
            cboProduto.setSelectedIndex(0);

            function.carregaTabela(CadEntDAO.ListaEntrada(), tblEntEst); //atualiza a tabela de empresa ao salvar registro

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    "Não foi possível salvar/alterar este registro.\n", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }


}//GEN-LAST:event_btnSalvarMouseClicked

    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
        // TODO add your handling code here:

        String sProduto;
        int iCodProd, end;

        sProduto = (String) cboProduto.getSelectedItem();

        end = sProduto.indexOf(" ");

        if (end == -1) {
            iCodProd = Integer.parseInt(sProduto);
        } else {
            iCodProd = Integer.parseInt(sProduto.substring(0, end));
        }

        try {

            clsFunctions function = new clsFunctions();

            clsCadEntradaEstDAO CadEntDAO = new clsCadEntradaEstDAO();

            //Cria modelo do jTable
            DefaultTableModel tableModel = (DefaultTableModel) tblEntEst.getModel();
            //Pego a linha selecionada
            int row = tblEntEst.getSelectedRow();
            //Se tiver linha selecionada
            if (row != -1) {
                //Pego o ID e a Desc do produto e jogo em sProduto
                sProduto = tableModel.getValueAt(row, 1).toString();
                //Acho o ID
                end = sProduto.indexOf(" ");

                if (end == -1) {
                    iCodProd = Integer.parseInt(sProduto);
                } else {
                    //Pego só o ID
                    iCodProd = Integer.parseInt(sProduto.substring(0, end));
                }
                //Envio a data e o ID para o método excluir o dado
                CadEntDAO.ExcluirEntrada(tableModel.getValueAt(row, 0).toString(), iCodProd);

            } else {
                CadEntDAO.ExcluirEntrada(txtDataEntrada.getText(), iCodProd);
            }

            txtNotaFiscal.setText("");
            txtQtdEntrada.setText("");
            txtDataEntrada.setText(function.fSysDate());
            cboProduto.setSelectedIndex(0);

            function.carregaTabela(CadEntDAO.ListaEntrada(), tblEntEst); //atualiza a tabela de empresa ao excluir registro

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    "Não foi possível realizar Exclusão.\n", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_btnExcluirMouseClicked

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
}//GEN-LAST:event_btnSairMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_btnSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            clsFunctions function = new clsFunctions();
            clsCadEntradaEstDAO CadEntradaDao = new clsCadEntradaEstDAO();

            cboProduto.removeAllItems(); //remove os itens que estão no combo

            function.carregaCombo(CadEntradaDao.ListaComboProduto(), cboProduto, "PRODUTO");

            function.carregaTabela(CadEntradaDao.ListaEntrada(), tblEntEst); //atualiza a tabela de empresa ao salvar registro

            txtNotaFiscal.setText("");
            txtQtdEntrada.setText("");
            txtDataEntrada.setText(function.fSysDate());
            cboProduto.setSelectedIndex(0);

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    "Ocorreram problemas ao abrir tela.\n", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_formWindowOpened

    private void txtNotaFiscalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNotaFiscalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotaFiscalKeyPressed

    private void cboProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboProdutoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cboProdutoMouseClicked

    private void cboProdutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboProdutoItemStateChanged
        // TODO add your handling code here:
        try {

            String sProduto;
            int iCodProd, end;

            sProduto = (String) cboProduto.getSelectedItem();

            end = sProduto.indexOf(" ");

            if (end == -1) {
                iCodProd = Integer.parseInt(sProduto);
            } else {
                iCodProd = Integer.parseInt(sProduto.substring(0, end));
            }

            clsCadEntradaEstDAO CadEntradaDAO = new clsCadEntradaEstDAO();
            clsFunctions function = new clsFunctions();

            if (!txtDataEntrada.getText().equals("")) {

                ResultSet rst = CadEntradaDAO.ConsultarEntrada(txtDataEntrada.getText(), iCodProd);

                if (rst.next()) {

                    txtNotaFiscal.setText(rst.getString("NF"));
                    txtQtdEntrada.setText(String.valueOf(rst.getDouble("QTD")).toString());
                } else {
                    txtNotaFiscal.setText("");
                    txtQtdEntrada.setText("");
                }

            }
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_cboProdutoItemStateChanged

    private void txtDataEntradaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataEntradaFocusLost
        // TODO add your handling code here:
        try {

            String sProduto;
            int iCodProd, end;

            sProduto = (String) cboProduto.getSelectedItem();

            end = sProduto.indexOf(" ");

            if (end == -1) {
                iCodProd = Integer.parseInt(sProduto);
            } else {
                iCodProd = Integer.parseInt(sProduto.substring(0, end));
            }

            clsCadEntradaEstDAO CadEntradaDAO = new clsCadEntradaEstDAO();
            clsFunctions function = new clsFunctions();

            if (!txtDataEntrada.getText().equals("")) {

                ResultSet rst = CadEntradaDAO.ConsultarEntrada(txtDataEntrada.getText(), iCodProd);

                if (rst.next()) {

                    txtNotaFiscal.setText(rst.getString("NF"));
                    txtQtdEntrada.setText(String.valueOf(rst.getDouble("QTD")).toString());
                } else {
                    txtNotaFiscal.setText("");
                    txtQtdEntrada.setText("");
                }


            }
        } catch (Exception ex) {
        }

    }//GEN-LAST:event_txtDataEntradaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmCadEntradaEst().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cboProduto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblEntEst;
    private javax.swing.JFormattedTextField txtDataEntrada;
    private javax.swing.JFormattedTextField txtNotaFiscal;
    private javax.swing.JFormattedTextField txtQtdEntrada;
    // End of variables declaration//GEN-END:variables
}
