/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmCadEmpresa.java
 *
 * Created on 27/03/2011, 02:18:14
 */
package cadastros;

import conexao.clsFunctions;
import ferramentas.clsFerramentaEmpresa;
import ferramentas.clsValidacao;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author AndreSAG
 */
public class frmCadEmpresa extends javax.swing.JFrame {

    /** Creates new form frmCadEmpresa */
    public frmCadEmpresa() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jSplitPane1 = new javax.swing.JSplitPane();
        optStatus = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        optAtivo = new javax.swing.JRadioButton();
        optInativo = new javax.swing.JRadioButton();
        txtCNPJEmpr = new javax.swing.JFormattedTextField();
        txtCodEmpresa = new javax.swing.JFormattedTextField();
        txtRazSocial = new javax.swing.JFormattedTextField();
        txtNomeFant = new javax.swing.JFormattedTextField();
        txtInscrEst = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMissao = new javax.swing.JEditorPane();
        lblObrigatório1 = new javax.swing.JLabel();
        lblObrigatório2 = new javax.swing.JLabel();
        lblObrigatório3 = new javax.swing.JLabel();
        lblObrigatório4 = new javax.swing.JLabel();
        lblObrigatório5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtContato = new javax.swing.JFormattedTextField();
        txtEmail = new javax.swing.JFormattedTextField();
        txtTel = new javax.swing.JFormattedTextField();
        txtCel = new javax.swing.JFormattedTextField();
        lblObrigatório = new javax.swing.JLabel();
        lblObrigatório11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cboEstado = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        cboCidade = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtRua = new javax.swing.JFormattedTextField();
        txtNumero = new javax.swing.JFormattedTextField();
        txtBairro = new javax.swing.JFormattedTextField();
        lblObrigatório6 = new javax.swing.JLabel();
        lblObrigatório7 = new javax.swing.JLabel();
        lblObrigatório8 = new javax.swing.JLabel();
        lblObrigatório9 = new javax.swing.JLabel();
        lblObrigatório10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmpresa = new javax.swing.JTable();
        txtDataCad = new javax.swing.JFormattedTextField();
        btnNovo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Empresa");
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados da Empresa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Código");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 31, 68, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Razão Social");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 62, 68, 20));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Fantasia");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 93, 68, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("CNPJ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 158, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Insc. Estadual");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 124, -1, 20));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Razão Negócio");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 189, -1, -1));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Situação:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 288, -1, -1));

        optStatus.add(optAtivo);
        optAtivo.setText("Ativo");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, optInativo, org.jdesktop.beansbinding.ELProperty.create("${action.enabled}"), optAtivo, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        optAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optAtivoActionPerformed(evt);
            }
        });
        jPanel1.add(optAtivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 284, -1, -1));

        optStatus.add(optInativo);
        optInativo.setText("Inativo");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, optAtivo, org.jdesktop.beansbinding.ELProperty.create("${action.enabled}"), optInativo, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        optInativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optInativoActionPerformed(evt);
            }
        });
        jPanel1.add(optInativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 284, -1, -1));

        txtCNPJEmpr.setFormatterFactory(clsValidacao.setFormatoCnpj());
        txtCNPJEmpr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCNPJEmprKeyTyped(evt);
            }
        });
        jPanel1.add(txtCNPJEmpr, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 155, 161, -1));

        txtCodEmpresa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodEmpresaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodEmpresaKeyTyped(evt);
            }
        });
        jPanel1.add(txtCodEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 31, 53, -1));

        txtRazSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRazSocialKeyTyped(evt);
            }
        });
        jPanel1.add(txtRazSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 62, 280, -1));

        txtNomeFant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeFantActionPerformed(evt);
            }
        });
        txtNomeFant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeFantKeyTyped(evt);
            }
        });
        jPanel1.add(txtNomeFant, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 93, 280, -1));

        txtInscrEst.setFormatterFactory(clsValidacao.setFormatoInscrEst());
        txtInscrEst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInscrEstKeyTyped(evt);
            }
        });
        jPanel1.add(txtInscrEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 124, 280, -1));

        txtMissao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMissaoKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtMissao);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 280, 80));

        lblObrigatório1.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblObrigatório1.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatório1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObrigatório1.setText("*");
        lblObrigatório1.setToolTipText("Campo Obrigatório!");
        jPanel1.add(lblObrigatório1, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 60, 10, 20));

        lblObrigatório2.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblObrigatório2.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatório2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObrigatório2.setText("*");
        lblObrigatório2.setToolTipText("Campo Obrigatório!");
        jPanel1.add(lblObrigatório2, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 90, 10, 20));

        lblObrigatório3.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblObrigatório3.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatório3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObrigatório3.setText("*");
        lblObrigatório3.setToolTipText("Campo Obrigatório!");
        jPanel1.add(lblObrigatório3, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 150, 10, 20));

        lblObrigatório4.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblObrigatório4.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatório4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObrigatório4.setText("*");
        lblObrigatório4.setToolTipText("Campo Obrigatório!");
        jPanel1.add(lblObrigatório4, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 120, 10, 20));

        lblObrigatório5.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblObrigatório5.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatório5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObrigatório5.setText("*");
        lblObrigatório5.setToolTipText("Campo Obrigatório!");
        jPanel1.add(lblObrigatório5, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 286, 10, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 400, 320));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Nome");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 29, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Telefone");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 91, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("E-mail");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 60, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Celular");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 91, -1, -1));

        txtContato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContatoKeyTyped(evt);
            }
        });
        jPanel2.add(txtContato, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 26, 295, -1));

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 57, 295, -1));

        txtTel.setFormatterFactory(clsValidacao.setFormatoTelefone());
        txtTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelKeyTyped(evt);
            }
        });
        jPanel2.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 88, 112, -1));

        txtCel.setFormatterFactory(clsValidacao.setFormatoTelefone());
        txtCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelActionPerformed(evt);
            }
        });
        txtCel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelKeyTyped(evt);
            }
        });
        jPanel2.add(txtCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 118, -1));

        lblObrigatório.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblObrigatório.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatório.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObrigatório.setText("*");
        lblObrigatório.setToolTipText("Campo Obrigatório!");
        jPanel2.add(lblObrigatório, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 86, 10, 20));

        lblObrigatório11.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblObrigatório11.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatório11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObrigatório11.setText("*");
        lblObrigatório11.setToolTipText("Campo Obrigatório!");
        jPanel2.add(lblObrigatório11, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 55, 10, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 390, 130));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cboEstado.setFont(new java.awt.Font("Arial", 0, 11));
        cboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboEstadoMouseClicked(evt);
            }
        });
        cboEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboEstadoItemStateChanged(evt);
            }
        });
        cboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEstadoActionPerformed(evt);
            }
        });
        jPanel3.add(cboEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 93, 65, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Bairro");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 65, -1, -1));

        cboCidade.setFont(new java.awt.Font("Arial", 0, 11));
        cboCidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCidade.setEnabled(false);
        jPanel3.add(cboCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 93, 157, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("nº");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 65, 25, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Rua");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 34, 20, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("UF");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 96, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Cidade");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 96, -1, -1));

        txtRua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRuaKeyTyped(evt);
            }
        });
        jPanel3.add(txtRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 31, 323, -1));

        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroKeyTyped(evt);
            }
        });
        jPanel3.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 62, 65, -1));

        txtBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBairroKeyTyped(evt);
            }
        });
        jPanel3.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 62, 202, -1));

        lblObrigatório6.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblObrigatório6.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatório6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObrigatório6.setText("*");
        lblObrigatório6.setToolTipText("Campo Obrigatório!");
        jPanel3.add(lblObrigatório6, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 30, 10, 20));

        lblObrigatório7.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblObrigatório7.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatório7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObrigatório7.setText("*");
        lblObrigatório7.setToolTipText("Campo Obrigatório!");
        jPanel3.add(lblObrigatório7, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 60, 10, 20));

        lblObrigatório8.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblObrigatório8.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatório8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObrigatório8.setText("*");
        lblObrigatório8.setToolTipText("Campo Obrigatório!");
        jPanel3.add(lblObrigatório8, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 60, 10, 20));

        lblObrigatório9.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblObrigatório9.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatório9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObrigatório9.setText("*");
        lblObrigatório9.setToolTipText("Campo Obrigatório!");
        jPanel3.add(lblObrigatório9, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 90, 10, 20));

        lblObrigatório10.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblObrigatório10.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatório10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObrigatório10.setText("*");
        lblObrigatório10.setToolTipText("Campo Obrigatório!");
        jPanel3.add(lblObrigatório10, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 90, 10, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 390, 128));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel14.setText("Cadastrado em:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        tblEmpresa.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tblEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "CNPJ", "CIDADE", "UF", "CONTATO", "DATA CADASTRO", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmpresa.setName("tblEmpresa"); // NOI18N
        tblEmpresa.getTableHeader().setResizingAllowed(false);
        tblEmpresa.getTableHeader().setReorderingAllowed(false);
        tblEmpresa.setUpdateSelectionOnSort(false);
        jScrollPane2.setViewportView(tblEmpresa);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 800, 160));

        try {
            txtDataCad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataCad.setEnabled(false);
        getContentPane().add(txtDataCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 70, -1));

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_novo.png"))); // NOI18N
        btnNovo.setToolTipText("Novo");
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoMouseClicked(evt);
            }
        });
        getContentPane().add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 10, 520));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_salvar.png"))); // NOI18N
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 30, 30));

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_excluir.png"))); // NOI18N
        btnExcluir.setToolTipText("Excluir");
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, 30, 30));

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_sair.png"))); // NOI18N
        btnSair.setToolTipText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 30, 30));

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_pesquisar.png"))); // NOI18N
        btnPesquisar.setToolTipText("Pesquisar");
        btnPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseClicked(evt);
            }
        });
        getContentPane().add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 30, 30));

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_alterar.png"))); // NOI18N
        btnAlterar.setToolTipText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarMouseClicked(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 30, 30));

        bindingGroup.bind();

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-888)/2, (screenSize.height-576)/2, 888, 576);
    }// </editor-fold>//GEN-END:initComponents

    private void cboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEstadoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {

            clsFerramentaEmpresa fEmpresa = new clsFerramentaEmpresa();
            fEmpresa.HabilitaNovo(txtCodEmpresa, txtRazSocial, txtNomeFant, txtInscrEst, txtCNPJEmpr, txtMissao, optAtivo, txtRua,
                    txtNumero, txtBairro, cboEstado, cboCidade, txtContato, txtEmail, txtTel, txtCel, btnAlterar, btnSalvar);

            cboEstado.removeAllItems(); //remove os itens que estão no combo
            cboCidade.removeAllItems();

            clsFunctions function = new clsFunctions();
            clsCadEmpresaDAO cadEmpr = new clsCadEmpresaDAO();

            function.carregaCombo(cadEmpr.ListaEstado(), cboEstado, "UF");
            function.carregaTabela(cadEmpr.ListaEmpresa(), tblEmpresa); //atualiza a tabela de empresa ao salvar registro

            function.dataSistema(txtDataCad);


        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    "Ocorreram problemas ao abrir tela.\n", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_formWindowOpened

    private void cboEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboEstadoMouseClicked
        // TODO add your handling code here:

        try {
            clsFunctions function = new clsFunctions();

            clsCadEmpresaDAO cadEmpr = new clsCadEmpresaDAO();

            Object sUF = cboEstado.getSelectedItem();

            cboEstado.getSelectedItem();

            function.carregaCombo(cadEmpr.ListaCidade(sUF), cboCidade, "NOME");

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    "Ocorreram problemas ao abrir tela.\n" + err.getMessage() + ")", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cboEstadoMouseClicked

    private void cboEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboEstadoItemStateChanged
        // TODO add your handling code here:
        try {
            clsFunctions function = new clsFunctions();

            clsCadEmpresaDAO cadEmpr = new clsCadEmpresaDAO();

            Object sUF = cboEstado.getSelectedItem();
            cboEstado.getSelectedItem();
            System.out.print(cboEstado.getSelectedIndex());

            if ((cboEstado.getSelectedIndex() == 0)) {

                cboCidade.setEnabled(false);
                cboCidade.removeAllItems();

            } else {
                cboCidade.setEnabled(true);
                function.carregaCombo(cadEmpr.ListaCidade(sUF), cboCidade, "NOME");
            }

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    "Ocorreram problemas ao abrir tela.\n", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cboEstadoItemStateChanged

    private void btnNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseClicked
        // TODO add your handling code here:
        try {
            clsFunctions function = new clsFunctions();

            boolean bStatus = optAtivo.isEnabled();

            clsFerramentaEmpresa fEmpresa = new clsFerramentaEmpresa();
            fEmpresa.HabilitaNovo(txtCodEmpresa, txtRazSocial, txtNomeFant, txtInscrEst, txtCNPJEmpr, txtMissao, optAtivo, txtRua, txtNumero, txtBairro,
                    cboEstado, cboCidade, txtContato, txtEmail, txtTel, txtCel, btnAlterar, btnSalvar);

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    err.getMessage(), "Atenção!", JOptionPane.ERROR_MESSAGE);
        }


}//GEN-LAST:event_btnNovoMouseClicked

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        // TODO add your handling code here:
        if (btnSalvar.isEnabled() != false) {
            if (txtRazSocial.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha o Campo Razão Social!",
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);
                txtRazSocial.grabFocus();
            } else if (txtNomeFant.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha o Campo Fantasia!",
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);
                txtNomeFant.grabFocus();
            } else if (txtInscrEst.getText().equals("___.___.___-____")) {
                JOptionPane.showMessageDialog(this, "Preencha o Campo Inscrição Estadual!",
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);
                txtInscrEst.grabFocus();
            } else if (txtCNPJEmpr.getText().equals("__.___.___/____-__")) {
                JOptionPane.showMessageDialog(this, "Preencha o Campo CNPJ!",
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);
                txtCNPJEmpr.grabFocus();
            } else if (txtRua.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha o Campo Rua!",
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);
                txtRua.grabFocus();
            } else if (txtNumero.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha o Campo Número!",
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);
                txtNumero.grabFocus();
            } else if (txtBairro.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha o Campo Bairro!",
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);
                txtBairro.grabFocus();
            } else if (cboEstado.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Escolha um estado!",
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);
                cboEstado.grabFocus();
            } else if (cboCidade.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Escolha uma Cidade!",
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);
                cboCidade.grabFocus();
            } else if (txtEmail.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha o Campo Email!",
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);
                txtEmail.grabFocus();
            } else if (!(txtEmail.getText().toLowerCase().matches(".+@.+\\.[a-z]+"))) {
                JOptionPane.showMessageDialog(this, "Digite um formato de email de válido!",
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);
                txtEmail.grabFocus();
            } else if (txtTel.getText().equals("(__)________")) {
                JOptionPane.showMessageDialog(this, "Preencha o campo telefone!",
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);
                txtTel.grabFocus();
            } else {

                try {


                    boolean bStatus;
                    if (optAtivo.isEnabled()) {
                        bStatus = true;
                    } else {
                        bStatus = false;
                    }

                    clsCadEmpresa CadEmpresa = new clsCadEmpresa(Integer.parseInt(txtCodEmpresa.getText()), txtDataCad.getText(), txtRazSocial.getText(),
                            txtNomeFant.getText(), txtInscrEst.getText(), txtCNPJEmpr.getText(),
                            txtMissao.getText(), txtRua.getText(), txtNumero.getText(),
                            txtBairro.getText(), cboEstado.getSelectedItem(), cboCidade.getSelectedItem(),
                            txtContato.getText(), txtEmail.getText(), txtTel.getText(), txtCel.getText(), bStatus);

                    clsCadEmpresaDAO CadEmpresaDAO = new clsCadEmpresaDAO();

                    CadEmpresaDAO.InserirEmpresa(CadEmpresa);

                    clsFerramentaEmpresa fEmpresa = new clsFerramentaEmpresa();
                    fEmpresa.HabilitaNovo(txtCodEmpresa, txtRazSocial, txtNomeFant, txtInscrEst, txtCNPJEmpr, txtMissao, optAtivo,
                            txtRua, txtNumero, txtBairro, cboEstado, cboCidade, txtContato, txtEmail, txtTel, txtCel, btnAlterar, btnSalvar);

                    clsFunctions function = new clsFunctions();
                    function.carregaTabela(CadEmpresaDAO.ListaEmpresa(), tblEmpresa); //atualiza a tabela de empresa ao salvar registro

                } catch (Exception err) {
                    JOptionPane.showMessageDialog(this,
                            "Não foi possível salvar/alterar este registro.\n" + err.getMessage(), "Atenção!", JOptionPane.ERROR_MESSAGE);
                }
            }
        }

}//GEN-LAST:event_btnSalvarMouseClicked
    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
        // TODO add your handling code here:

        try {
            clsFunctions function = new clsFunctions();

            int codigo = function.getRowTable(tblEmpresa);

            clsCadFuncionarioDAO FuncDAO = new clsCadFuncionarioDAO();
            System.out.print(FuncDAO.ConsultarFuncEmpresa(codigo));

            if (FuncDAO.ConsultarFuncEmpresa(codigo) == true) {
                JOptionPane.showMessageDialog(this,
                        "Impossível realizar exclusão, porque existem funcionários "
                        + "cadastrados para esta Empresa!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
            } else {


                clsCadEmpresaDAO CadEmpresaDAO = new clsCadEmpresaDAO();

                CadEmpresaDAO.ExcluiEmpresa(codigo);

                clsFerramentaEmpresa fEmpresa = new clsFerramentaEmpresa();
                fEmpresa.HabilitaNovo(txtCodEmpresa, txtRazSocial, txtNomeFant, txtInscrEst, txtCNPJEmpr, txtMissao, optAtivo,
                        txtRua, txtNumero, txtBairro, cboEstado, cboCidade, txtContato, txtEmail, txtTel, txtCel, btnAlterar, btnSalvar);


                function.carregaTabela(CadEmpresaDAO.ListaEmpresa(), tblEmpresa); //atualiza a tabela de empresa ao excluir registro
            }
        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    "Não foi possível realizar Exclusão.\n", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_btnExcluirMouseClicked

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
}//GEN-LAST:event_btnSairMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_btnSairActionPerformed

    private void txtCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelActionPerformed

    private void optAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optAtivoActionPerformed

    private void optInativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optInativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optInativoActionPerformed

    private void txtNomeFantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeFantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFantActionPerformed

    private void txtCodEmpresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodEmpresaKeyPressed
        // TODO add your handling code here:
        try {


            clsCadEmpresaDAO CadEmpresaDAO = new clsCadEmpresaDAO();
            clsFunctions function = new clsFunctions();

            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

                ResultSet rst = CadEmpresaDAO.ConsultarEmpresa(Integer.parseInt(txtCodEmpresa.getText()));

                if (rst.next()) {

                    txtRazSocial.setText(rst.getString("RAZ_SOCIAL"));
                    txtNomeFant.setText(rst.getString("NOME_FANTASIA"));
                    txtCNPJEmpr.setText(rst.getString("CNPJ"));
                    txtInscrEst.setText(rst.getString("INSC_EST"));

                    int begin;
                    int end;
                    String sEndereco;
                    //Peguei todo o endereço do banco na variável sEndereço
                    sEndereco = rst.getString("ENDERECO");

                    //Peguei a rua, ou seja, do início da variável até ':'
                    end = sEndereco.lastIndexOf(":");

                    txtRua.setText(sEndereco.substring(0, end));

                    //Peguei o número, ou seja, do ':' até ';'
                    begin = sEndereco.indexOf(":");
                    end = sEndereco.lastIndexOf(";");
                    txtNumero.setText(sEndereco.substring(begin + 1, end));

                    //Peguei o bairro, ou seja, do ':' até o final
                    begin = sEndereco.indexOf(";");
                    txtBairro.setText(sEndereco.substring(begin + 1));

                    cboEstado.setSelectedItem(rst.getString("UF_ESTADO"));
                    cboCidade.setEnabled(false);
                    cboCidade.setSelectedItem(rst.getString("CIDADE"));

                    txtMissao.setText(rst.getString("MISSAO"));
                    txtContato.setText(rst.getString("CONTATO"));
                    txtTel.setText(rst.getString("TELEFONE_CONT"));
                    txtCel.setText(rst.getString("CELULAR_CONT"));
                    txtEmail.setText(rst.getString("EMAIL_CONT"));
                    txtDataCad.setText(rst.getString("CADASTRATO"));

                    if ((rst.getBoolean("STATUS")) == true) {
                        optAtivo.setSelected(true);
                    } else {
                        optInativo.setSelected(true);
                    }

                    btnAlterar.setEnabled(true);

                } else {

                    clsFerramentaEmpresa fEmpresa = new clsFerramentaEmpresa();
                    fEmpresa.HabilitaNovo(txtCodEmpresa, txtRazSocial, txtNomeFant, txtInscrEst, txtCNPJEmpr, txtMissao, optAtivo,
                            txtRua, txtNumero, txtBairro, cboEstado, cboCidade, txtContato, txtEmail, txtTel, txtCel, btnSalvar, btnSalvar);
                }

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Empresa não cadastrada.\n", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtCodEmpresaKeyPressed

    private void btnPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseClicked
        // TODO add your handling code here:

        try {
            clsFerramentaEmpresa fEmpresa = new clsFerramentaEmpresa();
            fEmpresa.HabilitaPesquisa(txtCodEmpresa, txtRazSocial, txtNomeFant, txtInscrEst, txtCNPJEmpr, txtMissao, optAtivo, optInativo,
                    txtRua, txtNumero, txtBairro, cboEstado, cboCidade, txtContato, txtEmail, txtTel, txtCel, btnAlterar, btnSalvar);






        } catch (SQLException ex) {
            Logger.getLogger(frmCadEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPesquisarMouseClicked

    private void btnAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseClicked
        // TODO add your handling code here:
        if (btnAlterar.isEnabled() != false) {
            try {
                clsFerramentaEmpresa fEmpresa = new clsFerramentaEmpresa();
                fEmpresa.HabilitaAlteração(txtCodEmpresa, txtRazSocial, txtNomeFant, txtInscrEst, txtCNPJEmpr, txtMissao, optAtivo, optInativo,
                        txtRua, txtNumero, txtBairro, cboEstado, cboCidade, txtContato, txtEmail, txtTel, txtCel, btnSalvar);
                btnAlterar.setEnabled(false);






            } catch (SQLException ex) {
                Logger.getLogger(frmCadEmpresa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnAlterarMouseClicked

    private void txtCodEmpresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodEmpresaKeyTyped
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        int TamCampo = 4;
        Valida.TamanhoMax(txtCodEmpresa, evt, TamCampo);
        Valida.SomenteNumeros(txtCodEmpresa, evt);
    }//GEN-LAST:event_txtCodEmpresaKeyTyped

    private void txtRazSocialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRazSocialKeyTyped
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        int TamCampo = 30;
        Valida.TamanhoMax(txtRazSocial, evt, TamCampo);
        Valida.SomenteLetras(txtRazSocial, evt);
    }//GEN-LAST:event_txtRazSocialKeyTyped

    private void txtNomeFantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeFantKeyTyped
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        int TamCampo = 30;
        Valida.TamanhoMax(txtNomeFant, evt, TamCampo);
        Valida.SomenteNumeroLetras(txtNomeFant, evt);
    }//GEN-LAST:event_txtNomeFantKeyTyped

    private void txtInscrEstKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInscrEstKeyTyped
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        Valida.SomenteNumeros(txtInscrEst, evt);
    }//GEN-LAST:event_txtInscrEstKeyTyped

    private void txtCNPJEmprKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCNPJEmprKeyTyped
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        Valida.SomenteNumeros(txtCNPJEmpr, evt);
    }//GEN-LAST:event_txtCNPJEmprKeyTyped

    private void txtMissaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMissaoKeyTyped
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        int TamCampo = 150;
        Valida.TamanhoMax(txtMissao, evt, TamCampo);
        Valida.SomenteLetras(txtMissao, evt);
    }//GEN-LAST:event_txtMissaoKeyTyped

    private void txtRuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRuaKeyTyped
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        int TamCampo = 60;
        Valida.TamanhoMax(txtRua, evt, TamCampo);
        Valida.SomenteNumeroLetras(txtRua, evt);
    }//GEN-LAST:event_txtRuaKeyTyped

    private void txtNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyTyped
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        int TamCampo = 5;
        Valida.TamanhoMax(txtNumero, evt, TamCampo);
        Valida.SomenteNumeros(txtNumero, evt);
    }//GEN-LAST:event_txtNumeroKeyTyped

    private void txtBairroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroKeyTyped
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        int TamCampo = 35;
        Valida.TamanhoMax(txtBairro, evt, TamCampo);
        Valida.SomenteNumeroLetras(txtBairro, evt);
    }//GEN-LAST:event_txtBairroKeyTyped

    private void txtContatoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContatoKeyTyped
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        int TamCampo = 30;
        Valida.TamanhoMax(txtContato, evt, TamCampo);
        Valida.SomenteLetras(txtContato, evt);
    }//GEN-LAST:event_txtContatoKeyTyped

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        int TamCampo = 30;
        Valida.TamanhoMax(txtEmail, evt, TamCampo);
    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelKeyTyped
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        Valida.SomenteNumeros(txtTel, evt);
    }//GEN-LAST:event_txtTelKeyTyped

    private void txtCelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelKeyTyped
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        Valida.SomenteNumeros(txtCel, evt);
    }//GEN-LAST:event_txtCelKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmCadEmpresa().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cboCidade;
    private javax.swing.JComboBox cboEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblObrigatório;
    private javax.swing.JLabel lblObrigatório1;
    private javax.swing.JLabel lblObrigatório10;
    private javax.swing.JLabel lblObrigatório11;
    private javax.swing.JLabel lblObrigatório2;
    private javax.swing.JLabel lblObrigatório3;
    private javax.swing.JLabel lblObrigatório4;
    private javax.swing.JLabel lblObrigatório5;
    private javax.swing.JLabel lblObrigatório6;
    private javax.swing.JLabel lblObrigatório7;
    private javax.swing.JLabel lblObrigatório8;
    private javax.swing.JLabel lblObrigatório9;
    private javax.swing.JRadioButton optAtivo;
    private javax.swing.JRadioButton optInativo;
    private javax.swing.ButtonGroup optStatus;
    private javax.swing.JTable tblEmpresa;
    private javax.swing.JFormattedTextField txtBairro;
    private javax.swing.JFormattedTextField txtCNPJEmpr;
    private javax.swing.JFormattedTextField txtCel;
    private javax.swing.JFormattedTextField txtCodEmpresa;
    private javax.swing.JFormattedTextField txtContato;
    private javax.swing.JFormattedTextField txtDataCad;
    private javax.swing.JFormattedTextField txtEmail;
    private javax.swing.JFormattedTextField txtInscrEst;
    private javax.swing.JEditorPane txtMissao;
    private javax.swing.JFormattedTextField txtNomeFant;
    private javax.swing.JFormattedTextField txtNumero;
    private javax.swing.JFormattedTextField txtRazSocial;
    private javax.swing.JFormattedTextField txtRua;
    private javax.swing.JFormattedTextField txtTel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
