package cadastros;

import conexao.clsFunctions;
import ferramentas.clsFerramentaTurno;
import ferramentas.clsValidacao;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class frmCadTurno extends javax.swing.JFrame {

    /** Creates new form frmCadTurno */
    public frmCadTurno() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optTempo = new javax.swing.ButtonGroup();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodTurno = new javax.swing.JFormattedTextField();
        optOito = new javax.swing.JRadioButton();
        optSeis = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtHoraIni = new javax.swing.JFormattedTextField();
        txtObs = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnSair = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTurno = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Turno");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setName("frmCadTurno"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 359, -1, 10));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Turno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Observações");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, 15));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Código");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, 15));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Hora Inicial");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 70, 15));

        txtCodTurno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtCodTurno.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCodTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodTurnoActionPerformed(evt);
            }
        });
        txtCodTurno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodTurnoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodTurnoKeyTyped(evt);
            }
        });
        jPanel1.add(txtCodTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 45, -1));

        optTempo.add(optOito);
        optOito.setText("8 Horas");
        optOito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optOitoActionPerformed(evt);
            }
        });
        optOito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                optOitoKeyPressed(evt);
            }
        });
        jPanel1.add(optOito, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 55, -1, -1));

        optTempo.add(optSeis);
        optSeis.setSelected(true);
        optSeis.setText("6 Horas");
        optSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optSeisActionPerformed(evt);
            }
        });
        optSeis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                optSeisKeyPressed(evt);
            }
        });
        jPanel1.add(optSeis, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 55, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Tempo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 70, 15));

        txtHoraIni.setFormatterFactory(clsValidacao.setFormatoHora());
        txtHoraIni.setText("__:__:00"); // NOI18N
        txtHoraIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraIniActionPerformed(evt);
            }
        });
        txtHoraIni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHoraIniKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHoraIniKeyTyped(evt);
            }
        });
        jPanel1.add(txtHoraIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 60, -1));

        txtObs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtObsKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtObsKeyTyped(evt);
            }
        });
        jPanel1.add(txtObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 255, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 360, 160));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 330));

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_sair.png"))); // NOI18N
        btnSair.setToolTipText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 30, 30));

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_novo.png"))); // NOI18N
        btnNovo.setToolTipText("Novo");
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoMouseClicked(evt);
            }
        });
        getContentPane().add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_salvar.png"))); // NOI18N
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalvarMousePressed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 30, 30));

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_excluir.png"))); // NOI18N
        btnExcluir.setToolTipText("Excluir");
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, 30, 30));

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_alterar.png"))); // NOI18N
        btnAlterar.setToolTipText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAlterarMousePressed(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 30, 30));

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_pesquisar.png"))); // NOI18N
        btnPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseClicked(evt);
            }
        });
        getContentPane().add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 30, 30));

        tblTurno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTurno);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 360, 170));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-444)/2, (screenSize.height-391)/2, 444, 391);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        /*Para usar a classe de funções é necessário adicionar uma Exceção, para que se der alguma erro
         * o mesmo possa ser tratado.
         * Como não é possível alterar a linha que declara este método foi necessário inserir o função Try Catch
         */
        try {
            clsFerramentaTurno fTurno = new clsFerramentaTurno();
            fTurno.HabilitaNovo(txtCodTurno, txtHoraIni, txtObs, optSeis, optOito, btnSalvar, btnAlterar);

            clsFunctions function = new clsFunctions();
            clsCadTurnoDAO CadTurnoDao = new clsCadTurnoDAO();

            txtCodTurno.setText(Integer.toString(function.ProxRegistro("CC_CAD_TURNO", "ID_TURNO")));

            function.carregaTabela(CadTurnoDao.ListaTurno(), tblTurno); //carrega a tabela de turno ao abrir tela

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    "Ocorreram problemas ao abrir tela.\n(" + err.getMessage() + ")", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_formWindowOpened

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked

        // TODO add your handling code here:
        
        if (btnSalvar.isEnabled()!=false){

        try {
            clsFerramentaTurno fTurno = new clsFerramentaTurno();
            
            //Verifica validação dos campos
            if (txtHoraIni.getText().equals("  :  :00")) {
                JOptionPane.showMessageDialog(this, "Preencha o Campo Hora Inicial!",
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);
            } else if ((fTurno.verificaData(txtHoraIni.getText())) == false) {
                JOptionPane.showMessageDialog(this, "Hora Inválida", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                txtHoraIni.setText("");

            } else if (txtObs.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha o Campo Observações!!",
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);
            } else {


                //verifica qual option esta selecionado e transforma de boolean para inteiro
                boolean bStatus = optSeis.isSelected();

                int iStatus, valorHora;

                if (bStatus == true) {
                    iStatus = 1;
                    valorHora = 6;
                } else {
                    iStatus = 0;
                    valorHora = 8;
                }

                //valida data final
                String sdataFim;
                sdataFim = fTurno.alteraData(txtHoraIni.getText(), valorHora);

                clsCadTurno CadTurno = new clsCadTurno(Integer.parseInt(txtCodTurno.getText()),
                        txtHoraIni.getText(),
                        sdataFim,
                        txtObs.getText(),
                        iStatus);

                clsCadTurnoDAO CadTurnoDao = new clsCadTurnoDAO();


                CadTurnoDao.InserirTurno(CadTurno);

                fTurno.HabilitaNovo(txtCodTurno, txtHoraIni, txtObs, optSeis, optOito, btnSalvar, btnAlterar);

                clsFunctions function = new clsFunctions();
                function.carregaTabela(CadTurnoDao.ListaTurno(), tblTurno); //atualiza a tabela de turno ao salvar registro

            }//finaliza validação dos campos

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    "Não foi possível salvar/alterar este registro.\n(" + err.getMessage() + ")", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_btnSalvarMouseClicked

    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
        // TODO add your handling code here:
        try {
            clsFunctions function = new clsFunctions();

            int codigo = function.getRowTable(tblTurno);

            clsCadTurnoDAO CadTurnoDao = new clsCadTurnoDAO();

            CadTurnoDao.ExcluiTurno(codigo);

            txtCodTurno.setText(Integer.toString(function.ProxRegistro("CC_CAD_TURNO", "ID_TURNO")));
            txtHoraIni.setText("");
            txtObs.setText("");

            function.carregaTabela(CadTurnoDao.ListaTurno(), tblTurno); //atualiza a tabela de turno ao excluir registro

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    "Não foi possível realizar Exclusão!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);


        }
    }//GEN-LAST:event_btnExcluirMouseClicked

    private void btnNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseClicked
        // TODO add your handling code here:
        try {
            clsFerramentaTurno fTurno = new clsFerramentaTurno();

            fTurno.HabilitaNovo(txtCodTurno, txtHoraIni, txtObs, optSeis, optOito, btnSalvar, btnAlterar);
            fTurno.LimparTurno(txtCodTurno, txtHoraIni, txtObs);

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    err.getMessage(), "Atenção!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNovoMouseClicked

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
    }//GEN-LAST:event_btnSairMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed
    private void txtCodTurnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodTurnoKeyPressed
        // TODO add your handling code here:
        try {

            clsCadTurnoDAO CadTurnoDAO = new clsCadTurnoDAO();
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

                ResultSet rst = CadTurnoDAO.ConsultarTurno(Integer.parseInt(txtCodTurno.getText()));
                txtHoraIni.setText(rst.getString("HORA_INI"));
                txtObs.setText(rst.getString("OBS_TURNO"));


                if (rst.getBoolean("TEMPO") == true) {
                    optSeis.setSelected(true);

                } else {
                    optOito.setSelected(true);
                }
                btnAlterar.setEnabled(true);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "O turno com o Código: " + txtCodTurno.getText()
                    + ", não foi encontrado!", "Atenção", JOptionPane.INFORMATION_MESSAGE);




        }
    }//GEN-LAST:event_txtCodTurnoKeyPressed

    private void txtCodTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodTurnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodTurnoActionPerformed

    private void btnPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseClicked
        // TODO add your handling code here:

        try {
            clsFerramentaTurno fTurno = new clsFerramentaTurno();
            fTurno.HabilitaPesquisa(txtCodTurno, txtHoraIni, txtObs, optSeis, optOito, btnSalvar);
        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    err.getMessage(), "Atenção!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnPesquisarMouseClicked

    private void btnAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarMouseClicked

    private void optSeisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_optSeisKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_optSeisKeyPressed

    private void optOitoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_optOitoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_optOitoKeyPressed

    private void optOitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optOitoActionPerformed
        // TODO add your handling code here:
       /* try {
        int valorHora = 8;
        clsFerramentaTurno fTurno = new clsFerramentaTurno();
        fTurno.alteraData(txtHoraIni.getText(), valorHora, txtHoraFim);
        
        } catch (SQLException ex) {
        Logger.getLogger(frmCadTurno.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_optOitoActionPerformed

    private void optSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optSeisActionPerformed
        // TODO add your handling code here:
       /* try {
        int valorHora = 6;
        clsFerramentaTurno fTurno = new clsFerramentaTurno();
        fTurno.alteraData(txtHoraIni.getText(), valorHora, txtHoraFim);
        
        } catch (SQLException ex) {
        Logger.getLogger(frmCadTurno.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_optSeisActionPerformed

    private void txtHoraIniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoraIniKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraIniKeyTyped

    private void txtHoraIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraIniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraIniActionPerformed

    private void txtHoraIniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoraIniKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            evt.consume();
        }
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            evt.consume();
        }
    }//GEN-LAST:event_txtHoraIniKeyPressed

    private void btnSalvarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarMousePressed

    private void btnAlterarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMousePressed
        // TODO add your handling code here:
        if (btnAlterar.isEnabled()!=false){
        try {

            clsFerramentaTurno fTurno = new clsFerramentaTurno();
            fTurno.HabilitaAlteracao(txtCodTurno, txtHoraIni, txtObs, optSeis, optOito, btnSalvar, btnExcluir);

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    err.getMessage(), "Atenção!", JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_btnAlterarMousePressed

    private void txtObsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObsKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObsKeyPressed

    private void txtObsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObsKeyTyped
        // TODO add your handling code here:

        
            clsValidacao Valida = new clsValidacao();

            Valida.SomenteNumeroLetras(txtObs, evt);

            int tamCampo = 20;
            Valida.TamanhoMax(txtObs, evt, tamCampo);
        

    }//GEN-LAST:event_txtObsKeyTyped

    private void txtCodTurnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodTurnoKeyTyped
        // TODO add your handling code here:        

        
            clsValidacao Valida = new clsValidacao();
            Valida.SomenteNumeros(txtCodTurno, evt);
            
            int tamCampo = 4;
            Valida.TamanhoMax(txtCodTurno, evt, tamCampo);
            
        

    }//GEN-LAST:event_txtCodTurnoKeyTyped
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmCadTurno().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton optOito;
    private javax.swing.JRadioButton optSeis;
    private javax.swing.ButtonGroup optTempo;
    private javax.swing.JTable tblTurno;
    private javax.swing.JFormattedTextField txtCodTurno;
    private javax.swing.JFormattedTextField txtHoraIni;
    private javax.swing.JTextField txtObs;
    // End of variables declaration//GEN-END:variables
}
