/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmCadMarketing.java
 *
 * Created on 09/04/2011, 14:57:20
 */
package cadastros;

import conexao.clsFunctions;
import ferramentas.clsFerramentaMarketing;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AndreSAG
 */
public class frmCadMarketing extends javax.swing.JFrame {

    /** Creates new form frmCadMarketing */
    public frmCadMarketing() {
        initComponents();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    public int piProdMark;

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Empresa = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNotaFiscal = new javax.swing.JFormattedTextField();
        cboEmpresa = new javax.swing.JComboBox();
        Empresa3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCodMark = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMarketing = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        Empresa1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtQtd = new javax.swing.JFormattedTextField();
        txtDesc = new javax.swing.JFormattedTextField();
        Empresa2 = new javax.swing.JLabel();
        txtValor = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        btnSalvarProd = new javax.swing.JButton();
        btnNovoProd = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnAlterar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnSair2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnExcluirProd = new javax.swing.JButton();
        btnAlterarProd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdNota = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Marketing");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Marketing", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        Empresa.setFont(new java.awt.Font("Arial", 0, 11));
        Empresa.setText("Empresa");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel8.setText("Nota Fiscal");

        txtNotaFiscal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNotaFiscalKeyPressed(evt);
            }
        });

        cboEmpresa.setFont(new java.awt.Font("Arial", 0, 11));

        Empresa3.setFont(new java.awt.Font("Arial", 0, 11));
        Empresa3.setText("Data");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel10.setText("Código");

        txtCodMark.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodMarkKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Empresa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Empresa3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodMark, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCodMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8))
                    .addComponent(txtNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Empresa)
                    .addComponent(cboEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Empresa3)
                .addGap(9, 9, 9))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 11, 300, 160));

        tblMarketing.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tblMarketing.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMarketing.setName("tblMarketing"); // NOI18N
        tblMarketing.setUpdateSelectionOnSort(false);
        jScrollPane2.setViewportView(tblMarketing);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 530, 140));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        Empresa1.setFont(new java.awt.Font("Arial", 0, 11));
        Empresa1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Empresa1.setText("Quantidade");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Descrição");

        txtQtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQtdKeyPressed(evt);
            }
        });

        txtDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescKeyPressed(evt);
            }
        });

        Empresa2.setFont(new java.awt.Font("Arial", 0, 11));
        Empresa2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Empresa2.setText("Valor");

        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorKeyPressed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnSalvarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_salvar.png"))); // NOI18N
        btnSalvarProd.setToolTipText("Incluir produto na lista");
        btnSalvarProd.setEnabled(false);
        btnSalvarProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarProdMouseClicked(evt);
            }
        });

        btnNovoProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_novo.png"))); // NOI18N
        btnNovoProd.setToolTipText("Novo produto");
        btnNovoProd.setEnabled(false);
        btnNovoProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoProdMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnNovoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSalvarProd, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                    .addComponent(btnNovoProd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Empresa1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Empresa2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9)
                    .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Empresa1)
                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Empresa2)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 300, 160));

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_novo.png"))); // NOI18N
        btnNovo.setToolTipText("Novo");
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoMouseClicked(evt);
            }
        });
        getContentPane().add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 11, 30, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 11, 10, 470));

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_alterar.png"))); // NOI18N
        btnAlterar.setToolTipText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarMouseClicked(evt);
            }
        });
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 46, 30, 30));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_salvar.png"))); // NOI18N
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 81, 30, 30));

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_excluir.png"))); // NOI18N
        btnExcluir.setToolTipText("Excluir");
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 116, 30, 30));

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_pesquisar.png"))); // NOI18N
        btnPesquisar.setToolTipText("Pesquisa");
        btnPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseClicked(evt);
            }
        });
        getContentPane().add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 151, 30, 30));

        btnSair2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_sair.png"))); // NOI18N
        btnSair2.setToolTipText("Sair");
        btnSair2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSair2MouseClicked(evt);
            }
        });
        btnSair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 30, 30));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnExcluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_excluir.png"))); // NOI18N
        btnExcluirProd.setToolTipText("Excluir produto da lista");
        btnExcluirProd.setEnabled(false);
        btnExcluirProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirProdMouseClicked(evt);
            }
        });

        btnAlterarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_alterar.png"))); // NOI18N
        btnAlterarProd.setToolTipText("Alterar produto");
        btnAlterarProd.setEnabled(false);
        btnAlterarProd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAlterarProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarProdMouseClicked(evt);
            }
        });
        btnAlterarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnExcluirProd, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAlterarProd, 0, 0, Short.MAX_VALUE)
                    .addComponent(btnExcluirProd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 220, 30));

        tblProdNota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CÓD.", "PRODUTO", "QTD.", "VALOR"
            }
        ));
        tblProdNota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdNotaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblProdNotaMouseEntered(evt);
            }
        });
        tblProdNota.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblProdNotaFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(tblProdNota);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 220, 250));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setForeground(new java.awt.Color(0, 51, 201));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Produtos da nota");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 220, -1));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-614)/2, (screenSize.height-522)/2, 614, 522);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {

            cboEmpresa.removeAllItems(); //remove os itens que estão no combo

            clsFunctions function = new clsFunctions();
            clsCadMarketingDAO CadMarketingDao = new clsCadMarketingDAO();
            clsFerramentaMarketing fMarketing = new clsFerramentaMarketing();

            function.carregaCombo(CadMarketingDao.ListaComboEmpresa(), cboEmpresa, "EMPRESA");

            function.carregaTabela(CadMarketingDao.ListaMarketing(), tblMarketing); //atualiza a tabela de empresa ao salvar registro

            txtCodMark.setText(Integer.toString(function.ProxRegistro("CC_CAD_MARKETING", "ID_MARKETING")));

            fMarketing.HabilitaNovo(txtCodMark, txtNotaFiscal, cboEmpresa, txtData, txtDesc, txtQtd, txtValor, tblProdNota, btnAlterar, btnSalvar, btnExcluir);
            btnNovoProd.setEnabled(true);
            btnSalvarProd.setEnabled(true);
            btnAlterarProd.setEnabled(true);
            btnExcluirProd.setEnabled(true);

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    "Ocorreram problemas ao abrir tela.\n", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_formWindowOpened

    private void txtNotaFiscalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNotaFiscalKeyPressed
    }//GEN-LAST:event_txtNotaFiscalKeyPressed

    private void txtQtdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdKeyPressed

    private void txtDescKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescKeyPressed

    private void txtValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorKeyPressed

    private void btnNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseClicked
        // TODO add your handling code here:

        try {
            clsFerramentaMarketing fMarketing = new clsFerramentaMarketing();
            fMarketing.HabilitaNovo(txtCodMark, txtNotaFiscal, cboEmpresa, txtData, txtDesc, txtQtd, txtValor, tblProdNota, btnAlterar, btnSalvar, btnExcluir);
            btnNovoProd.setEnabled(true);
            btnSalvarProd.setEnabled(true);
            btnAlterarProd.setEnabled(true);
            btnExcluirProd.setEnabled(true);

        } catch (SQLException ex) {
            Logger.getLogger(frmCadEstacionamento.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_btnNovoMouseClicked

    private void btnAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseClicked
        // TODO add your handling code here:
        if (btnAlterar.isEnabled() != false) {
            try {
                clsFerramentaMarketing fMarketing = new clsFerramentaMarketing();
                fMarketing.HabilitaAlterar(txtCodMark, txtNotaFiscal, cboEmpresa, txtData, txtDesc, txtQtd, tblProdNota, txtValor, btnSalvar);
                btnNovoProd.setEnabled(true);
                btnSalvarProd.setEnabled(true);
                btnAlterarProd.setEnabled(true);
                btnExcluirProd.setEnabled(true);
            } catch (SQLException ex) {
                Logger.getLogger(frmCadEstacionamento.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
}//GEN-LAST:event_btnAlterarMouseClicked

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_btnAlterarActionPerformed

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked

        // TODO add your handling code here:

        String sMsg = "";

        if (btnSalvar.isEnabled() != false) {
            if (txtData.getDate() == null) {
                sMsg = "- Escolha uma data!\n";
            }
            if (txtNotaFiscal.getText().isEmpty()) {
                sMsg = sMsg + "- Digite o número da nota!\n";
            }
            if (cboEmpresa.getSelectedIndex() == 0) {
                sMsg = sMsg + "- Escolha a Empresa!\n";
            }

            if (!sMsg.equals("")) {

                JOptionPane.showMessageDialog(this,
                        "Mensagem:\n"
                        + sMsg, "Atenção!", JOptionPane.ERROR_MESSAGE);

            } else {

                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String sData = sdf.format(txtData.getDate()); // pego e transformo a data no padrão acima

                String sEmpresa;
                int iEmpresa, end;

                sEmpresa = (String) cboEmpresa.getSelectedItem();
                end = sEmpresa.indexOf(" ");

                if (end == -1) {
                    iEmpresa = Integer.parseInt(sEmpresa);
                } else {
                    iEmpresa = Integer.parseInt(sEmpresa.substring(0, end));
                }

                try {
                    clsFunctions function = new clsFunctions();

                    clsCadMarketing CadMarketing = new clsCadMarketing(Integer.parseInt(txtCodMark.getText()), txtNotaFiscal.getText(), iEmpresa, sData);

                    clsCadMarketingDAO CadMaketingDAO = new clsCadMarketingDAO();

                    CadMaketingDAO.InserirMarketing(CadMarketing);

                    clsFerramentaMarketing fMarketing = new clsFerramentaMarketing();

                    function.carregaTabela(CadMaketingDAO.ListaMarketing(), tblMarketing);

                } catch (Exception err) {
                    JOptionPane.showMessageDialog(this,
                            "Não foi possível salvar/alterar este registro.\n(" + err.getMessage() + ")", "Atenção!", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
}//GEN-LAST:event_btnSalvarMouseClicked

    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
        // TODO add your handling code here:
        if (btnExcluir.isEnabled() == true) {
            try {
                clsFunctions function = new clsFunctions();
                int iMarketing = 0;

                clsCadMarketingDAO CadMarketingDAO = new clsCadMarketingDAO();

                DefaultTableModel tableModel = (DefaultTableModel) tblMarketing.getModel();

                int row = tblMarketing.getSelectedRow();

                if (row != -1) {//se tiver linha selecionada, exclui da linha

                    iMarketing = Integer.parseInt(tableModel.getValueAt(row, 0).toString());
                    CadMarketingDAO.ExcluirMarketing(iMarketing);

                } else if (!txtCodMark.getText().isEmpty()) { //senão exclui do campo
                    CadMarketingDAO.ExcluirMarketing(Integer.parseInt(txtCodMark.getText()));

                } else {
                    JOptionPane.showMessageDialog(this,
                            "Selecione o dado na tabela ou digite um código a ser excluído.\n", "Atenção!", JOptionPane.ERROR_MESSAGE);
                }


                clsFerramentaMarketing fMarketing = new clsFerramentaMarketing();
                fMarketing.LimparTela(txtCodMark, txtNotaFiscal, cboEmpresa, txtData, txtDesc, txtQtd, txtValor, tblProdNota);

                function.carregaTabela(CadMarketingDAO.ListaMarketing(), tblMarketing); //atualiza a tabela de Contrato ao excluir registro
                function.carregaTabela(CadMarketingDAO.ListaProdMark(iMarketing), tblProdNota);

            } catch (Exception err) {
                JOptionPane.showMessageDialog(this,
                        "Não foi possível realizar Exlusão.\n(" + err.getMessage() + ")", "Atenção!", JOptionPane.ERROR_MESSAGE);
            }
        }
}//GEN-LAST:event_btnExcluirMouseClicked

    private void btnPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseClicked
        // TODO add your handling code here:
        try {

            clsFerramentaMarketing fMarketing = new clsFerramentaMarketing();

            fMarketing.LimparTela(txtCodMark, txtNotaFiscal, cboEmpresa, txtData, txtDesc, txtQtd, txtValor, tblProdNota);

            fMarketing.HabilitaPesquisa(txtCodMark, txtNotaFiscal, cboEmpresa, txtData, txtDesc, txtQtd, txtValor, tblProdNota, btnAlterar, btnSalvar, btnExcluir);
            btnNovoProd.setEnabled(false);
            btnSalvarProd.setEnabled(false);
            btnAlterarProd.setEnabled(false);
            btnExcluirProd.setEnabled(false);

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    err.getMessage(), "Atenção!", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_btnPesquisarMouseClicked

    private void btnSair2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSair2MouseClicked
}//GEN-LAST:event_btnSair2MouseClicked

    private void btnSair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_btnSair2ActionPerformed

    private void btnNovoProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoProdMouseClicked
        // TODO add your handling code here:
        if (btnNovoProd.isEnabled() != false) {
            txtDesc.setText(null);
            txtQtd.setText(null);
            txtValor.setText(null);
        }
}//GEN-LAST:event_btnNovoProdMouseClicked

    private void btnSalvarProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarProdMouseClicked
        // TODO add your handling code here:
        if (btnSalvarProd.isEnabled() != false) {
            String sMsg = "";

            try {

                if (txtDesc.getText().isEmpty()) {
                    sMsg = "- Informe o produto!\n";
                }
                if (txtQtd.getText().isEmpty()) {
                    sMsg = sMsg + "- Informe a quantidade!\n";
                }
                if (txtValor.getText().isEmpty()) {
                    sMsg = sMsg + "- Informe o valor!\n";
                }

                if (!sMsg.equals("")) {

                    JOptionPane.showMessageDialog(this,
                            "Mensagem:\n"
                            + sMsg, "Atenção!", JOptionPane.ERROR_MESSAGE);

                } else {

                    int iCodProd;

                    clsFunctions function = new clsFunctions();

                    if (piProdMark == 0) {
                        iCodProd = function.ProxRegistro("CC_CAD_MARK_PROD", "ID_PROD");
                    } else {
                        iCodProd = piProdMark;
                    }

                    clsCadMarketing CadMarketing = new clsCadMarketing(Integer.parseInt(txtCodMark.getText()),
                            iCodProd,
                            txtDesc.getText(),
                            Integer.parseInt(txtQtd.getText()),
                            Float.parseFloat(txtValor.getText()));

                    clsCadMarketingDAO CadMarketingDao = new clsCadMarketingDAO();

                    //não deixar salvar produtos sem ter o marketing salvo
                    //programar um maneira de não precisar fazer isso
                    btnSalvarMouseClicked(evt);

                    CadMarketingDao.InserirProduto(CadMarketing);

                    function.carregaTabela(CadMarketingDao.ListaProdMark(Integer.parseInt(txtCodMark.getText())), tblProdNota);

                    txtDesc.setText(null);
                    txtQtd.setText(null);
                    txtValor.setText(null);
                }
            } catch (Exception ex) {

                JOptionPane.showMessageDialog(this,
                        ex.getMessage(), "Atenção!", JOptionPane.ERROR_MESSAGE);
            }
        }
}//GEN-LAST:event_btnSalvarProdMouseClicked

    private void txtCodMarkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodMarkKeyPressed
        // TODO add your handling code here:
        try {

            clsCadMarketingDAO CadMarketingDao = new clsCadMarketingDAO();
            clsFunctions function = new clsFunctions();

            if (evt.getKeyCode() == evt.VK_ENTER) {

                System.out.println(txtNotaFiscal.getText());

                ResultSet rst = CadMarketingDao.ConsultarMarketing(Integer.parseInt(txtCodMark.getText()));

                if (rst.next()) {
                    txtNotaFiscal.setText(rst.getString("NOTA_FISCAL"));
                    cboEmpresa.setSelectedItem(rst.getString("EMPRESA"));
                    txtData.setDate(rst.getDate("DATA"));
                    function.carregaTabela(CadMarketingDao.ListaProdMark(Integer.parseInt(txtCodMark.getText())), tblProdNota);
                    btnAlterar.setEnabled(true);

                } else {
                    txtNotaFiscal.setText("");
                    cboEmpresa.setSelectedIndex(0);
                    txtData.setDate(null);
                    btnAlterar.setEnabled(false);
                    tblProdNota.removeAll(); //deveria remover os itens do grid
                    function.carregaTabela(CadMarketingDao.ListaProdMark(0), tblProdNota);
                }

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Marketing não cadastrado.\n", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtCodMarkKeyPressed

    private void btnExcluirProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirProdMouseClicked
        // TODO add your handling code here:
        if (btnExcluirProd.isEnabled() != false) {
            try {

                clsFunctions function = new clsFunctions();

                clsCadMarketingDAO CadMarketingDao = new clsCadMarketingDAO();

                DefaultTableModel tableModel = (DefaultTableModel) tblProdNota.getModel();

                int iProdMark;

                int row = tblProdNota.getSelectedRow();

                if (row != -1) {//se tiver linha selecionada, exclui da linha

                    iProdMark = Integer.parseInt(tableModel.getValueAt(row, 0).toString());
                    CadMarketingDao.ExcluirProdMark(iProdMark);

                } else {
                    JOptionPane.showMessageDialog(this,
                            "Selecione o dado a ser excluído na tabela.\n", "Atenção!", JOptionPane.ERROR_MESSAGE);
                }

                function.carregaTabela(CadMarketingDao.ListaProdMark(Integer.parseInt(txtCodMark.getText())), tblProdNota);

                txtDesc.setText(null);
                txtQtd.setText(null);
                txtValor.setText(null);

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this,
                        ex.getMessage(), "Atenção!", JOptionPane.INFORMATION_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnExcluirProdMouseClicked

    private void tblProdNotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdNotaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblProdNotaMouseClicked

    private void tblProdNotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdNotaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblProdNotaMouseEntered

    private void tblProdNotaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblProdNotaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tblProdNotaFocusGained

    private void btnAlterarProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarProdMouseClicked
        // TODO add your handling code here:
        if (btnAlterarProd.isEnabled() != false) {
            try {
                clsFunctions function = new clsFunctions();
                clsCadMarketingDAO CadMarketingDao = new clsCadMarketingDAO();

                DefaultTableModel tableModel = (DefaultTableModel) tblProdNota.getModel();

                //int iProdMark;
                int row = tblProdNota.getSelectedRow();

                if (row != -1) {//se tiver linha selecionada, exclui da linha

                    piProdMark = Integer.parseInt(tableModel.getValueAt(row, 0).toString());

                    ResultSet rst = CadMarketingDao.ConsultarProdMark(piProdMark);

                    rst.first();
                    txtDesc.setText(rst.getString("DESC_PROD"));
                    txtQtd.setText(rst.getString("QTD_PROD"));
                    txtValor.setText(rst.getString("VALOR_PROD"));

                } else {
                    piProdMark = 0;
                    JOptionPane.showMessageDialog(this,
                            "Selecione o dado a ser alterado.\n", "Atenção!", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this,
                        ex.getMessage(), "Atenção!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAlterarProdMouseClicked

    private void btnAlterarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmCadMarketing().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Empresa;
    private javax.swing.JLabel Empresa1;
    private javax.swing.JLabel Empresa2;
    private javax.swing.JLabel Empresa3;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAlterarProd;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExcluirProd;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnNovoProd;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair2;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSalvarProd;
    private javax.swing.JComboBox cboEmpresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblMarketing;
    private javax.swing.JTable tblProdNota;
    private javax.swing.JFormattedTextField txtCodMark;
    private javax.swing.JFormattedTextField txtDesc;
    private javax.swing.JFormattedTextField txtNotaFiscal;
    private javax.swing.JFormattedTextField txtQtd;
    private javax.swing.JFormattedTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
