package cadastros;

import conexao.clsFunctions;
import ferramentas.clsFerramentaUsuario;
import ferramentas.clsValidacao;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmCadUsuario.java
 *
 * Created on 05/03/2011, 01:12:33
 */
/**
 *
 * @author Andre Garcia
 */
public class frmCadUsuario extends javax.swing.JFrame {

    /** Creates new form frmCadUsuario */
    public frmCadUsuario() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCodUsuario = new javax.swing.JFormattedTextField();
        txtLogin = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboTpAcesso = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        txtConfirmacao = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        btnSair = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtDataCad = new javax.swing.JFormattedTextField();
        btnPesquisar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Usuário");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setName("frmCadUsuario"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsuario.setName("tblUsuario"); // NOI18N
        tblUsuario.setUpdateSelectionOnSort(false);
        jScrollPane2.setViewportView(tblUsuario);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 357, 142));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 359, -1, 10));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel1.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jPanel1HierarchyChanged(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel4.setText("Nome de Usuário");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 60, -1, 15));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel1.setText("Código");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 30, -1, 15));

        txtCodUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodUsuario.setEnabled(false);
        txtCodUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodUsuarioActionPerformed(evt);
            }
        });
        txtCodUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodUsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(txtCodUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 30, 45, -1));

        txtLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLoginKeyTyped(evt);
            }
        });
        jPanel1.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 60, 150, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel5.setText("Senha");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 90, -1, 15));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel6.setText("Confirmação");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 120, -1, 15));

        cboTpAcesso.setFont(new java.awt.Font("Arial", 0, 11));
        cboTpAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTpAcessoActionPerformed(evt);
            }
        });
        jPanel1.add(cboTpAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 150, 134, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel2.setText("Tipo de Acesso");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 150, -1, 15));

        txtSenha.setText("jPasswordField1");
        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSenhaKeyTyped(evt);
            }
        });
        jPanel1.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 90, 150, -1));

        txtConfirmacao.setText("jPasswordField2");
        jPanel1.add(txtConfirmacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 120, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 360, 190));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 10, 370));

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_sair.png"))); // NOI18N
        btnSair.setToolTipText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 30, 30));

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_novo.png"))); // NOI18N
        btnNovo.setToolTipText("Novo");
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoMouseClicked(evt);
            }
        });
        getContentPane().add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_salvar.png"))); // NOI18N
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 30, 30));

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_excluir.png"))); // NOI18N
        btnExcluir.setToolTipText("Excluir");
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, 30, 30));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel14.setText("Data Cadastro:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        try {
            txtDataCad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataCad.setEnabled(false);
        getContentPane().add(txtDataCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 70, -1));

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_pesquisar.png"))); // NOI18N
        btnPesquisar.setToolTipText("Pesquisar");
        btnPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseClicked(evt);
            }
        });
        getContentPane().add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 30, 30));

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_alterar.png"))); // NOI18N
        btnAlterar.setToolTipText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarMouseClicked(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 30, 30));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-444)/2, (screenSize.height-432)/2, 444, 432);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        /*Para usar a classe de funções é necessário adicionar uma Exceção, para que se der alguma erro
         * o mesmo possa ser tratado.
         * Como não é possível alterar a linha que declara este método foi necessário inserir o função Try Catch
         */

        try {
            clsFunctions function = new clsFunctions();
            clsCadUsuarioDAO CadUsuarioDao = new clsCadUsuarioDAO();

            clsFerramentaUsuario fUsuario = new clsFerramentaUsuario();
            fUsuario.HabilitarNovo(txtCodUsuario, txtLogin, txtSenha, txtConfirmacao, cboTpAcesso, btnAlterar, btnSalvar);

            function.dataSistema(txtDataCad);

            cboTpAcesso.addItem("1 - Administrativo");
            cboTpAcesso.addItem("2 - Gerencial");
            cboTpAcesso.setSelectedIndex(0);

            function.carregaTabela(CadUsuarioDao.ListaUsuario(), tblUsuario); //carrega a tabela de Usuario ao abrir tela

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    "Ocorreram problemas ao abrir tela.\n(" + err.getMessage() + ")", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_formWindowOpened

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        if (btnSalvar.isEnabled() == true) {

            if (txtLogin.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Preencha o Campo Login", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
                txtLogin.grabFocus();
            } else if (txtSenha.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Preencha o Campo Senha!!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
                txtSenha.grabFocus();
            } else if (txtSenha.getText().length() < 6) {
                JOptionPane.showMessageDialog(this,
                        "Digite uma senha com 6 ou mais Caracteres!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
                txtSenha.grabFocus();
            } else if (!(txtSenha.getText().matches("([a-zA-Z]+)[0-9]+([a-zA-Z0-9])*"))) {
                JOptionPane.showMessageDialog(this,
                        "A senha deve conter letras e números!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
                txtSenha.grabFocus();
            } else if (txtConfirmacao.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Confirme sua Senha", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
                txtConfirmacao.grabFocus();
            } else if (!(txtSenha.getText().equals(txtConfirmacao.getText()))) {
                JOptionPane.showMessageDialog(this,
                        "Não foi possível Salvar/Alterar o registro. Senhas diferentes!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
            } else {
                // TODO add your handling code here:
                String sTpAcesso, sAux;
                int end;

                //Jogo a empresa selecionada no combo na variável sEmpresa
                sAux = (String) cboTpAcesso.getSelectedItem();

                //Pego o index do primeira ocorrência de um "-"
                end = sAux.indexOf(" ");

                //Se não encontrou o "-"...
                if (end == -1) {
                    //... É porque só tem o número da empresa
                    //Então jogo o número na variável iCodEmpr
                    sTpAcesso = sAux;
                } else {
                    //Senão uso o END para saber aonde está o número da empresa e jogo na variável iCodEmpr
                    System.out.println(sAux.substring(0, end));
                    sTpAcesso = sAux.substring(0, end);
                }

                try {



                    clsFunctions function = new clsFunctions();

                    clsCadUsuario CadUsuario = new clsCadUsuario(Integer.parseInt(txtCodUsuario.getText()),
                            txtLogin.getText(),
                            txtSenha.getText(),
                            txtDataCad.getText(),
                            sTpAcesso);

                    clsCadUsuarioDAO CadUsuarioDao = new clsCadUsuarioDAO();

                    CadUsuarioDao.InserirUsuario(CadUsuario);

                    clsFerramentaUsuario fUsuario = new clsFerramentaUsuario();
                    fUsuario.HabilitarNovo(txtCodUsuario, txtLogin, txtSenha, txtConfirmacao, cboTpAcesso, btnAlterar, btnSalvar);

                    function.carregaTabela(CadUsuarioDao.ListaUsuario(), tblUsuario); //atualiza a tabela de Usuario ao salvar registro


                } catch (Exception err) {
                    JOptionPane.showMessageDialog(this,
                            "Não foi possível salvar/alterar este registro.\n(" + err.getMessage() + ")", "Atenção!", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnSalvarMouseClicked

    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
        // TODO add your handling code here:
        try {
            clsFunctions function = new clsFunctions();

            int codigo = function.getRowTable(tblUsuario);

            clsCadUsuarioDAO CadUsuarioDao = new clsCadUsuarioDAO();

            CadUsuarioDao.ExcluiUsuario(codigo);

            clsFerramentaUsuario fUsuario = new clsFerramentaUsuario();
            fUsuario.HabilitarNovo(txtCodUsuario, txtLogin, txtSenha, txtConfirmacao, cboTpAcesso, btnAlterar, btnSalvar);

            function.carregaTabela(CadUsuarioDao.ListaUsuario(), tblUsuario); //atualiza a tabela de Usuario ao excluir registro

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    "Não foi possível realizar Exclusão.\n(" + err.getMessage() + ")", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirMouseClicked

    private void btnNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseClicked
        // TODO add your handling code here:
        try {

            clsFerramentaUsuario fUsuario = new clsFerramentaUsuario();
            fUsuario.HabilitarNovo(txtCodUsuario, txtLogin, txtSenha, txtConfirmacao, cboTpAcesso, btnAlterar, btnSalvar);

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    err.getMessage(), "Atenção!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNovoMouseClicked

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
    }//GEN-LAST:event_btnSairMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtCodUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodUsuarioKeyPressed
        // TODO add your handling code here:
        try {
            clsCadUsuarioDAO CadUsuarioDao = new clsCadUsuarioDAO();
            clsFunctions function = new clsFunctions();

            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

                ResultSet rst = CadUsuarioDao.ConsultarUsuario(Integer.parseInt(txtCodUsuario.getText()));

                rst.next();

                txtLogin.setText(rst.getString("LOGIN"));
                txtSenha.setText(rst.getString("SENHA"));
                txtConfirmacao.setText(rst.getString("SENHA"));
                //txtDataCad.setText(rst.getString("CADASTRATO"));
                cboTpAcesso.setSelectedIndex(rst.getInt("TIPO_USUARIO") - 1); //o índice começa do ZERO


                btnAlterar.setEnabled(true);
            } 
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Usuario não cadastrado.", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
            txtCodUsuario.setText(null);
        }
    }//GEN-LAST:event_txtCodUsuarioKeyPressed

    private void txtCodUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodUsuarioActionPerformed

    private void cboTpAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTpAcessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTpAcessoActionPerformed

    private void btnPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseClicked
        // TODO add your handling code here:
        clsFerramentaUsuario fUsuario = new clsFerramentaUsuario();
        fUsuario.HabilitarPesquisa(txtCodUsuario, txtLogin, txtSenha, txtConfirmacao, cboTpAcesso, btnAlterar, btnSalvar);

    }//GEN-LAST:event_btnPesquisarMouseClicked

    private void btnAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseClicked
        // TODO add your handling code here:
        if (btnAlterar.isEnabled() == true) {
            if (!(txtCodUsuario.getText().isEmpty())) {
                clsFerramentaUsuario fUsuario = new clsFerramentaUsuario();
                fUsuario.HabilitaAlteracao(txtCodUsuario, txtLogin, txtSenha, txtConfirmacao, cboTpAcesso, btnAlterar, btnSalvar);
            }
        }
    }//GEN-LAST:event_btnAlterarMouseClicked

    private void txtLoginKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginKeyTyped
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        int TamCampo = 10;
        Valida.LetrasLogin(txtLogin, evt);
        Valida.TamanhoMax(txtLogin, evt, TamCampo);

    }//GEN-LAST:event_txtLoginKeyTyped

    private void txtSenhaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyTyped
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        int TamCampo = 15;
        Valida.NumeroLetrasSenha(txtLogin, evt);
        Valida.TamanhoMax(txtLogin, evt, TamCampo);
    }//GEN-LAST:event_txtSenhaKeyTyped

    private void jPanel1HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jPanel1HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1HierarchyChanged

    private void txtCodUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodUsuarioKeyTyped
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        int TamCampo = 3;
        Valida.SomenteNumeros(txtCodUsuario, evt);
        Valida.TamanhoMax(txtCodUsuario, evt, TamCampo);
    }//GEN-LAST:event_txtCodUsuarioKeyTyped
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmCadUsuario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cboTpAcesso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblUsuario;
    private javax.swing.JFormattedTextField txtCodUsuario;
    private javax.swing.JPasswordField txtConfirmacao;
    private javax.swing.JFormattedTextField txtDataCad;
    private javax.swing.JFormattedTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
