/*

FALTA TRATAR OS CAMPOS DATAS, ADICIONAR UM CALENDARIO E FAZER VALIDAÇAO
 *
 * EXEMPLO SE O CAMPO DATA FIM NAO EH MAIOR Q O CAMPO DATA INICIO
 * EXEMPLO SE A DATA ESCOLHIDA JA NAO ESTA COM UM EVENTO PROGRAMADO

 */
package cadastros;

import com.toedter.calendar.JCalendar;
import conexao.clsFunctions;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import ferramentas.clsFerramentaEvento;
import ferramentas.clsValidacao;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

public class frmCadEventos extends javax.swing.JFrame {

    public frmCadEventos() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        optPessoa = new javax.swing.ButtonGroup();
        txtDataCad = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodEvento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        lblObrigatorio1 = new javax.swing.JLabel();
        lblObrigatorio2 = new javax.swing.JLabel();
        lblObrigatorio3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNome = new javax.swing.JFormattedTextField();
        txtEmail = new javax.swing.JFormattedTextField();
        txtTel = new javax.swing.JFormattedTextField();
        txtCel = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        optFisica = new javax.swing.JRadioButton();
        optJuridica = new javax.swing.JRadioButton();
        lblObrigatorio = new javax.swing.JLabel();
        lblObrigatorio4 = new javax.swing.JLabel();
        lblObrigatorio5 = new javax.swing.JLabel();
        lblObrigatorio6 = new javax.swing.JLabel();
        lblObrigatorio7 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        txtCnpj = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnSair = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEvento = new javax.swing.JTable();
        btnPesquisar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Eventos");
        setLocationByPlatform(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        try {
            txtDataCad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataCad.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDataCad.setDropMode(javax.swing.DropMode.INSERT);
        txtDataCad.setEnabled(false);
        getContentPane().add(txtDataCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 71, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Evento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setDoubleBuffered(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Código");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 68, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Data Início");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 68, 20));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Data Fim");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 68, 20));

        txtCodEvento.setEnabled(false);
        txtCodEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodEventoActionPerformed(evt);
            }
        });
        txtCodEvento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodEventoKeyPressed(evt);
            }
        });
        jPanel1.add(txtCodEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 50, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Valor (R$)");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 68, 20));

        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorKeyTyped(evt);
            }
        });
        jPanel1.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 100, -1));

        lblObrigatorio1.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblObrigatorio1.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatorio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObrigatorio1.setText("*");
        lblObrigatorio1.setToolTipText("Campo Obrigatório");
        jPanel1.add(lblObrigatorio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 10, 15));

        lblObrigatorio2.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblObrigatorio2.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatorio2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObrigatorio2.setText("*");
        lblObrigatorio2.setToolTipText("Campo Obrigatório");
        jPanel1.add(lblObrigatorio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 10, 15));

        lblObrigatorio3.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblObrigatorio3.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatorio3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObrigatorio3.setText("*");
        lblObrigatorio3.setToolTipText("Campo Obrigatório");
        jPanel1.add(lblObrigatorio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 10, 15));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 240, 170));
        jPanel1.getAccessibleContext().setAccessibleName(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Responsável pelo Evento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Nome/Empresa");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 80, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Telefone");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 80, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("E-mail");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 80, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Celular");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 80, -1));

        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeKeyTyped(evt);
            }
        });
        jPanel2.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 320, -1));

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 159, -1));

        txtTel.setFormatterFactory(clsValidacao.setFormatoTelefone());
        jPanel2.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 160, -1));

        txtCel.setFormatterFactory(clsValidacao.setFormatoTelefone());
        jPanel2.add(txtCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 160, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("CNPJ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("CPF");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Física/Jurídica:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, -1));

        optPessoa.add(optFisica);
        optFisica.setText("Física");
        optFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optFisicaActionPerformed(evt);
            }
        });
        jPanel2.add(optFisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 25, -1, -1));

        optPessoa.add(optJuridica);
        optJuridica.setText("Jurídica");
        optJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optJuridicaActionPerformed(evt);
            }
        });
        jPanel2.add(optJuridica, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 25, -1, -1));

        lblObrigatorio.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblObrigatorio.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObrigatorio.setText("*");
        lblObrigatorio.setToolTipText("Campo Obrigatório");
        jPanel2.add(lblObrigatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 10, 15));

        lblObrigatorio4.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblObrigatorio4.setForeground(new java.awt.Color(0, 0, 255));
        lblObrigatorio4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObrigatorio4.setText("*");
        lblObrigatorio4.setToolTipText("Preencher o campo CPF ou CNPJ!");
        jPanel2.add(lblObrigatorio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 10, 15));

        lblObrigatorio5.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblObrigatorio5.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatorio5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObrigatorio5.setText("*");
        lblObrigatorio5.setToolTipText("Campo Obrigatório");
        jPanel2.add(lblObrigatorio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 10, 15));

        lblObrigatorio6.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblObrigatorio6.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatorio6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObrigatorio6.setText("*");
        lblObrigatorio6.setToolTipText("Campo Obrigatório");
        jPanel2.add(lblObrigatorio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 10, 15));

        lblObrigatorio7.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblObrigatorio7.setForeground(new java.awt.Color(0, 0, 255));
        lblObrigatorio7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObrigatorio7.setText("*");
        lblObrigatorio7.setToolTipText("Preencher o campo CPF ou CNPJ!");
        jPanel2.add(lblObrigatorio7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 10, 15));

        txtCpf.setFormatterFactory(clsValidacao.setFormatoCPF());
        jPanel2.add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 160, -1));

        txtCnpj.setFormatterFactory(clsValidacao.setFormatoCnpj());
        jPanel2.add(txtCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 160, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 450, 260));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel14.setText("Cadastrado em:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 10, 17, 490));

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_sair.png"))); // NOI18N
        btnSair.setToolTipText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 30, 30));

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_novo.png"))); // NOI18N
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoMouseClicked(evt);
            }
        });
        getContentPane().add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_salvar.png"))); // NOI18N
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 30, 30));

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_excluir.png"))); // NOI18N
        btnExcluir.setToolTipText("Excluir");
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, 30, 30));

        tblEvento.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tblEvento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13"
            }
        ));
        tblEvento.setName("tblEvento"); // NOI18N
        tblEvento.setUpdateSelectionOnSort(false);
        jScrollPane2.setViewportView(tblEvento);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 690, 178));

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_pesquisar.png"))); // NOI18N
        btnPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseClicked(evt);
            }
        });
        getContentPane().add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 30, 30));

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_alterar.png"))); // NOI18N
        btnAlterar.setEnabled(false);
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarMouseClicked(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 30, 30));

        getAccessibleContext().setAccessibleName(null);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-784)/2, (screenSize.height-546)/2, 784, 546);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            clsFerramentaEvento fEvento = new clsFerramentaEvento();
            fEvento.HabilitarNovo(txtCodEvento, jDataIni, jDataFim, txtValor, optFisica, optJuridica, txtCpf, txtCnpj, txtNome, txtEmail, txtTel, txtCel, btnAlterar, btnSalvar);

            clsCadEventoDAO cadEventoDAO = new clsCadEventoDAO();
            clsFunctions function = new clsFunctions();

            function.carregaTabela(cadEventoDAO.ListaEvento(), tblEvento);
            function.dataSistema(txtDataCad);


        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    "Ocorreram problemas ao abrir tela.\n(" + err.getMessage() + ")", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_formWindowOpened

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSairMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseClicked
        // TODO add your handling code here:
        try {

            clsFerramentaEvento fEvento = new clsFerramentaEvento();
            fEvento.HabilitarNovo(txtCodEvento, jDataIni, jDataFim, txtValor, optFisica, optJuridica, txtCpf, txtCnpj, txtNome, txtEmail, txtTel, txtCel, btnAlterar, btnSalvar);

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    err.getMessage(), "Atenção!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNovoMouseClicked

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        // TODO add your handling code here:

        if (btnSalvar.isEnabled() == true) {

            if (jDataIni.getDate() == null) {
                JOptionPane.showMessageDialog(this,
                        "Escolha uma data de início válida!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
            } else if (jDataFim.getDate() == null) {
                JOptionPane.showMessageDialog(this,
                        "Escolha uma data de fim válida!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
            } else if ((txtValor.getText().isEmpty())) {
                JOptionPane.showMessageDialog(this,
                        "Preencha o campo valor!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
                txtValor.grabFocus();
                /*} else if ((txtValor.getText().matches("[0-9]+|([0-9]+\\,[0-9][0-9])"))) {
                JOptionPane.showMessageDialog(this,
                "Preencha um valor válido!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
                txtValor.grabFocus();*/
            } else if ((optFisica.isSelected() == false) && (optJuridica.isSelected() == false)) {
                JOptionPane.showMessageDialog(this,
                        "Escolha um tipo de pessoa (Fisíca ou Jurídica)!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
            } else if ((txtCpf.getText().equals("___.___.___-__")) && (txtCnpj.getText().equals("__.___.___/____-__"))) {
                JOptionPane.showMessageDialog(this,
                        "Preencha o campo CPF ou CNPJ!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
            } else if (txtNome.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Preencha o campo Nome da Empresa/Pessoa Física!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
                txtNome.grabFocus();
            } else if (!(txtEmail.getText().toLowerCase().matches(".+@.+\\.[a-z]+")) && !(txtEmail.getText().isEmpty())) {
                JOptionPane.showMessageDialog(this, "Digite um formato de email de válido!",
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);
                txtEmail.grabFocus();

            } else if (txtTel.getText().equals("(__)________")) {
                JOptionPane.showMessageDialog(this,
                        "Preencha o campo Telefone!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
                txtTel.grabFocus();
            } else {

                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String dataIni = sdf.format(jDataIni.getDate()); // pego e transformo a data no padrão acima
                String dataFim = sdf.format(jDataFim.getDate());
                // Date date = (Date) sdf.parse(data); // aqui se quiser voltar para o tipo Date

                try {
                    clsFunctions function = new clsFunctions();



                    clsCadEvento cadEvento = new clsCadEvento(Integer.parseInt(txtCodEvento.getText()),
                            dataIni,
                            dataFim,
                            txtCnpj.getText(),
                            txtCpf.getText(),
                            Float.parseFloat((txtValor.getText()).replace(",", ".")),
                            txtNome.getText(),
                            txtTel.getText(),
                            txtCel.getText(),
                            txtEmail.getText(),
                            txtDataCad.getText());


                    clsCadEventoDAO CadEventoDAO = new clsCadEventoDAO();

                    CadEventoDAO.InserirEventos(cadEvento);
                    function.carregaTabela(CadEventoDAO.ListaEvento(), tblEvento);

                    clsFerramentaEvento fEvento = new clsFerramentaEvento();
                    fEvento.HabilitarNovo(txtCodEvento, jDataIni, jDataFim, txtValor, optFisica, optJuridica, txtCpf, txtCnpj,
                            txtNome, txtEmail, txtTel, txtCel, btnAlterar, btnSalvar);

                } catch (Exception err) {
                    JOptionPane.showMessageDialog(this,
                            "Não foi possível salvar/alterar este registro.\n(" + err.getMessage() + ")", "Atenção!", JOptionPane.ERROR_MESSAGE);
                }
            }
        }

    }//GEN-LAST:event_btnSalvarMouseClicked

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtCodEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodEventoActionPerformed

    private void txtCodEventoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodEventoKeyPressed
        // TODO add your handling code here:
        try {
            clsCadEventoDAO cadEventoDAO = new clsCadEventoDAO();
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

                ResultSet rst = cadEventoDAO.ConsultarEvento(Integer.parseInt(txtCodEvento.getText()));

                jDataIni.setDate(rst.getDate("DATA_INI"));
                jDataFim.setDate(rst.getDate("DATA_FIM"));
                txtValor.setText(rst.getString("VLR_LOC"));

                if (!(rst.getString("CNPJ_REQ").equals("__.___.___/____-__"))) {
                    optJuridica.setSelected(true);
                    txtCnpj.setText(rst.getString("CNPJ_REQ"));
                    txtCpf.setText(null);
                } else {
                    optFisica.setSelected(true);
                    txtCpf.setText(rst.getString("CPF_REQ"));
                    txtCnpj.setText(null);
                }

                txtNome.setText(rst.getString("RESP_EVENTO"));
                txtEmail.setText(rst.getString("EMAIL_RESP"));
                txtTel.setText(rst.getString("TELEFONE_RESP"));
                txtCel.setText(rst.getString("CELULAR_RESP"));
                txtDataCad.setText(rst.getString("DATA_CAD"));
            } else {
                clsFerramentaEvento fEvento = new clsFerramentaEvento();
                fEvento.LimparEvento(txtCodEvento, jDataIni, jDataFim, txtValor, optFisica, optJuridica, txtCpf, txtCnpj,
                        txtNome, txtEmail, txtTel, txtCel);

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Loja com o cóigo: " + txtCodEvento.getText() + ", Não Cadastrada!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
            btnAlterar.setEnabled(false);
        }
    }//GEN-LAST:event_txtCodEventoKeyPressed

    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
        // TODO add your handling code here:
        try {
            clsFunctions function = new clsFunctions();
            clsCadEventoDAO cadEventoDAO = new clsCadEventoDAO();

            int codigo = function.getRowTable(tblEvento);

            cadEventoDAO.ExcluiEvento(codigo);

            clsFerramentaEvento fEvento = new clsFerramentaEvento();
            fEvento.HabilitarNovo(txtCodEvento, jDataIni, jDataFim, txtValor, optFisica, optJuridica, txtCpf, txtCnpj, txtNome, txtEmail, txtTel, txtCel, btnAlterar, btnSalvar);


            function.carregaTabela(cadEventoDAO.ListaEvento(), tblEvento); //atualiza a tabela de turno ao excluir registro

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    "Não foi possível realizar Exclusão.\n(" + err.getMessage() + ")", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirMouseClicked

    private void optFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optFisicaActionPerformed
        // TODO add your handling code here:
        if (optFisica.isEnabled() == true) {
            txtCpf.setEnabled(true);
            txtCpf.setText("___.___.___-__");
            txtCnpj.setEnabled(false);
            txtCnpj.setText(null);
            txtCnpj.setText("__.___.___/____-__");
        }
    }//GEN-LAST:event_optFisicaActionPerformed

    private void optJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optJuridicaActionPerformed
        // TODO add your handling code here:
        if (optJuridica.isEnabled() == true) {
            txtCnpj.setEnabled(true);
            txtCnpj.setText("__.___.___/____-__");
            txtCpf.setEnabled(false);
            txtCpf.setText(null);
            txtCpf.setText("___.___.___-__");

        }
    }//GEN-LAST:event_optJuridicaActionPerformed

    private void btnPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseClicked
        // TODO add your handling code here:
        txtCodEvento.setText("");
        clsFerramentaEvento fEvento = new clsFerramentaEvento();
        fEvento.HabilitaPesquisar(txtCodEvento, jDataIni, jDataFim, txtValor, optFisica, optJuridica, txtCpf, txtCnpj, txtNome,
                txtEmail, txtTel, txtCel, btnAlterar, btnSalvar);
    }//GEN-LAST:event_btnPesquisarMouseClicked

    private void btnAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseClicked
        // TODO add your handling code here:
        if (btnAlterar.isEnabled() == true) {
            if (!(txtCodEvento.getText().isEmpty())) {
                clsFerramentaEvento fEvento = new clsFerramentaEvento();
                fEvento.HabilitaAlteracao(txtCodEvento, jDataIni, jDataFim, txtValor, optFisica, optJuridica, txtCpf, txtCnpj, txtNome,
                        txtEmail, txtTel, txtCel, btnAlterar, btnSalvar);
            }
        }
    }//GEN-LAST:event_btnAlterarMouseClicked

    private void txtValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyTyped
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        int TamCampo = 8;
        Valida.TamanhoMax(txtValor, evt, TamCampo);
        Valida.SomenteNumerosVirgulas(txtValor, evt);
        
        
    }//GEN-LAST:event_txtValorKeyTyped

    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        int TamCampo = 30;
        Valida.TamanhoMax(txtNome, evt, TamCampo);
        Valida.SomenteNumeroLetras(txtNome, evt);

    }//GEN-LAST:event_txtNomeKeyTyped

    private void jDataIniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDataIniFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jDataIniFocusLost

    private void txtValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyPressed
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        Valida.BlockPaste(evt);
    }//GEN-LAST:event_txtValorKeyPressed

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        Valida.BlockPaste(evt);
    }//GEN-LAST:event_txtNomeKeyPressed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        Valida.BlockPaste(evt);
    }//GEN-LAST:event_txtEmailKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmCadEventos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblObrigatorio;
    private javax.swing.JLabel lblObrigatorio1;
    private javax.swing.JLabel lblObrigatorio2;
    private javax.swing.JLabel lblObrigatorio3;
    private javax.swing.JLabel lblObrigatorio4;
    private javax.swing.JLabel lblObrigatorio5;
    private javax.swing.JLabel lblObrigatorio6;
    private javax.swing.JLabel lblObrigatorio7;
    private javax.swing.JRadioButton optFisica;
    private javax.swing.JRadioButton optJuridica;
    private javax.swing.ButtonGroup optPessoa;
    private javax.swing.JTable tblEvento;
    private javax.swing.JFormattedTextField txtCel;
    private javax.swing.JFormattedTextField txtCnpj;
    private javax.swing.JTextField txtCodEvento;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtDataCad;
    private javax.swing.JFormattedTextField txtEmail;
    private javax.swing.JFormattedTextField txtNome;
    private javax.swing.JFormattedTextField txtTel;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
