package cadastros;

import conexao.clsFunctions;
import ferramentas.clsFerramentaSetor;
import ferramentas.clsValidacao;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

public class frmCadSetor extends javax.swing.JFrame {

    /** Creates new form frmCadTurno */
    public frmCadSetor() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optStatus = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSetor = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodSetor = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JEditorPane();
        txtTamanho = new javax.swing.JTextField();
        optInativo = new javax.swing.JRadioButton();
        optAtivo = new javax.swing.JRadioButton();
        txtValor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnSair = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Setores");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setName("frmCadTurno"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblSetor.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tblSetor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSetor.setName("tblSetor"); // NOI18N
        tblSetor.setUpdateSelectionOnSort(false);
        jScrollPane2.setViewportView(tblSetor);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 357, 142));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 359, -1, 10));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Setor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Tamanho");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 180, 66, 20));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Código");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 30, 66, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Valor (R$)");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 150, 66, 20));

        txtCodSetor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtCodSetor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodSetor.setEnabled(false);
        txtCodSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodSetorActionPerformed(evt);
            }
        });
        txtCodSetor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodSetorKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodSetorKeyTyped(evt);
            }
        });
        jPanel1.add(txtCodSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 50, -1));

        txtDesc.setPreferredSize(new java.awt.Dimension(106, 40));
        txtDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtDesc);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 230, 80));

        txtTamanho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTamanhoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTamanhoKeyTyped(evt);
            }
        });
        jPanel1.add(txtTamanho, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 70, 20));

        optStatus.add(optInativo);
        optInativo.setText("Inativo");
        jPanel1.add(optInativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, 14));

        optStatus.add(optAtivo);
        optAtivo.setText("Ativo");
        jPanel1.add(optAtivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, 14));

        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorKeyTyped(evt);
            }
        });
        jPanel1.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 70, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Descrição");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 60, 66, 20));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Status");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 210, 66, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 360, 240));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 390));

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_sair.png"))); // NOI18N
        btnSair.setToolTipText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 30, 30));

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_novo.png"))); // NOI18N
        btnNovo.setToolTipText("Novo");
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoMouseClicked(evt);
            }
        });
        getContentPane().add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_salvar.png"))); // NOI18N
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 30, 30));

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_excluir.png"))); // NOI18N
        btnExcluir.setToolTipText("Excluir");
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, 30, 30));

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_pesquisar.png"))); // NOI18N
        btnPesquisar.setToolTipText("Pesquisar");
        btnPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseEntered(evt);
            }
        });
        getContentPane().add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 30, 30));

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_alterar.png"))); // NOI18N
        btnAlterar.setToolTipText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarMouseClicked(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 30, 30));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-444)/2, (screenSize.height-453)/2, 444, 453);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        /*Para usar a classe de funções é necessário adicionar uma Exceção, para que se der alguma erro
         * o mesmo possa ser tratado.
         * Como não é possível alterar a linha que declara este método foi necessário inserir o função Try Catch
         */

        try {
            clsFerramentaSetor fSetor = new clsFerramentaSetor();
            fSetor.HabilitaNovo(txtCodSetor, txtDesc, txtValor, txtTamanho, optAtivo, optInativo, btnAlterar);

            clsFunctions function = new clsFunctions();
            clsCadSetorDAO cadSetorDAO = new clsCadSetorDAO();
            function.carregaTabela(cadSetorDAO.ListaSetor(), tblSetor); //carrega a tabela de turno ao abrir tela

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    "Ocorreram problemas ao abrir tela.\n(" + err.getMessage() + ")", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_formWindowOpened

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked

        // TODO add your handling code here:
        if (btnSalvar.isEnabled() == true) {

            if (txtCodSetor.getText().equals("")) {
                
                JOptionPane.showMessageDialog(this,
                        "Preencha o campo código!!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
                txtCodSetor.grabFocus();
            } else if (txtDesc.getText().equals("")) {
                JOptionPane.showMessageDialog(this,
                        "Preencha o campo com a descrição sobre o Setor!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
                txtDesc.grabFocus();

            } else if (txtValor.getText().equals("")) {
                JOptionPane.showMessageDialog(this,
                        "Preencha o campo com o Valor do Setor!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
                txtValor.grabFocus();
            } else if (txtTamanho.getText().equals("")) {
                JOptionPane.showMessageDialog(this,
                        "Preencha o campo com o tamanho do Setor!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
                txtTamanho.grabFocus();
            } else {
                try {

                    boolean bStatus = optAtivo.isSelected();
                    int iStatus;
                    if (bStatus == true) {
                        iStatus = 1;
                    } else {
                        iStatus = 0;
                    }

                    clsFunctions function = new clsFunctions();

                    clsCadSetor cadSetor = new clsCadSetor(Integer.parseInt(txtCodSetor.getText()),
                            txtDesc.getText(),
                            Float.parseFloat(txtValor.getText().replace(",", ".")),
                            Float.parseFloat(txtTamanho.getText().replace(",", ".")),
                            iStatus);

                    clsCadSetorDAO cadSetorDAO = new clsCadSetorDAO();

                    cadSetorDAO.InserirSetor(cadSetor);
                    function.carregaTabela(cadSetorDAO.ListaSetor(), tblSetor);

                    clsFerramentaSetor fSetor = new clsFerramentaSetor();
                    fSetor.HabilitaNovo(txtCodSetor, txtDesc, txtValor, txtTamanho, optAtivo, optInativo, btnAlterar);

                } catch (Exception err) {
                    JOptionPane.showMessageDialog(this,
                            "Não foi possível salvar/alterar este registro.\n(" + err.getMessage() + ")", "Atenção!", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnSalvarMouseClicked

    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
        // TODO add your handling code here:
        try {
            clsFunctions function = new clsFunctions();
            clsCadSetorDAO cadSetorDAO = new clsCadSetorDAO();

            int iCodigo = function.getRowTable(tblSetor);
            cadSetorDAO.ExcluiSetor(iCodigo);

            clsFerramentaSetor fSetor = new clsFerramentaSetor();
            fSetor.HabilitaNovo(txtCodSetor, txtDesc, txtValor, txtTamanho, optAtivo, optInativo, btnAlterar);

            function.carregaTabela(cadSetorDAO.ListaSetor(), tblSetor); //atualiza a tabela de turno ao excluir registro

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    "Não foi possível realizar Exlusão.\n(" + err.getMessage() + ")", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirMouseClicked

    private void btnNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseClicked
        // TODO add your handling code here:
        try {
            clsFerramentaSetor fSetor = new clsFerramentaSetor();

            fSetor.HabilitaNovo(txtCodSetor, txtDesc, txtValor, txtTamanho, optAtivo, optInativo, btnAlterar);


        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    err.getMessage(), "Atenção!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNovoMouseClicked

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
    }//GEN-LAST:event_btnSairMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtCodSetorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodSetorKeyPressed
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        Valida.BlockPaste(evt);
        try {
            clsCadSetorDAO CadSetorDao = new clsCadSetorDAO();
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

                ResultSet rst = CadSetorDao.ConsultarSetor(Integer.parseInt(txtCodSetor.getText()));

                txtDesc.setText(rst.getString("DESC_LOCAL"));
                txtValor.setText(rst.getString("VLR_LOC"));
                txtTamanho.setText(rst.getString("SET_MEDIDA"));
                if (rst.getBoolean("STATUS") == true) {
                    optAtivo.setSelected(true);

                } else {
                    optInativo.setSelected(true);
                }

                btnAlterar.setEnabled(true);


            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Turno com o código: " + txtCodSetor.getText() + ",Não Cadastrado!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
            txtCodSetor.setText(null);

        }
    }//GEN-LAST:event_txtCodSetorKeyPressed

    private void txtCodSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodSetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodSetorActionPerformed

    private void btnPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseClicked
        // TODO add your handling code here:

        try {
            clsFerramentaSetor fSetor = new clsFerramentaSetor();
            fSetor.HabilitaPesquisa(txtCodSetor, txtDesc, txtValor, txtTamanho, optAtivo, optInativo, btnAlterar, btnSalvar);
        } catch (SQLException ex) {
            Logger.getLogger(frmCadSetor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPesquisarMouseClicked

    private void btnAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseClicked
        // TODO add your handling code here:
        if (btnAlterar.isEnabled() == true) {
            if (!(txtCodSetor.getText().equals(""))) {
                clsFerramentaSetor fSetor = new clsFerramentaSetor();
                fSetor.HabilitaAlterar(txtCodSetor, txtDesc, txtValor, txtTamanho, optAtivo, optInativo, btnAlterar, btnSalvar);
            }
        }
    }//GEN-LAST:event_btnAlterarMouseClicked

    private void btnPesquisarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarMouseEntered

    private void txtCodSetorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodSetorKeyTyped
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        int TamCampo = 4;
        Valida.TamanhoMax(txtCodSetor, evt, TamCampo);
        Valida.SomenteNumeros(txtCodSetor, evt);

    }//GEN-LAST:event_txtCodSetorKeyTyped

    private void txtDescKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescKeyTyped
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        int TamCampo = 255;
        Valida.TamanhoMax(txtDesc, evt, TamCampo);
    }//GEN-LAST:event_txtDescKeyTyped

    private void txtDescKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescKeyPressed
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        Valida.BlockPaste(evt);

    }//GEN-LAST:event_txtDescKeyPressed

    private void txtValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyTyped
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        int TamCampo = 8;
        Valida.TamanhoMax(txtTamanho, evt, TamCampo);
        Valida.SomenteNumerosVirgulas(txtTamanho, evt);

    }//GEN-LAST:event_txtValorKeyTyped

    private void txtValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyPressed
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        Valida.BlockPaste(evt);
    }//GEN-LAST:event_txtValorKeyPressed

    private void txtTamanhoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTamanhoKeyPressed
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        Valida.BlockPaste(evt);
    }//GEN-LAST:event_txtTamanhoKeyPressed

    private void txtTamanhoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTamanhoKeyTyped
        // TODO add your handling code here:
        clsValidacao Valida = new clsValidacao();
        int TamCampo = 5;
        Valida.TamanhoMax(txtTamanho, evt, TamCampo);
        Valida.SomenteNumeros(txtTamanho, evt);
    }//GEN-LAST:event_txtTamanhoKeyTyped
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmCadSetor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton optAtivo;
    private javax.swing.JRadioButton optInativo;
    private javax.swing.ButtonGroup optStatus;
    private javax.swing.JTable tblSetor;
    private javax.swing.JFormattedTextField txtCodSetor;
    private javax.swing.JEditorPane txtDesc;
    private javax.swing.JTextField txtTamanho;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
