package cadastros;

import conexao.clsFunctions;
import ferramentas.clsFerramentaContrato;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frmCadContrato extends javax.swing.JFrame {

    /** Creates new form frmCadContrato */
    public frmCadContrato() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optStatus = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblContrato = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboLoja = new javax.swing.JComboBox();
        cboSetor = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txtCodContrato = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtDataIni = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        txtDataFim = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDiaPgto = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtVlrParcela = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        txtRespLoja = new javax.swing.JTextField();
        txtRespShop = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnAlterar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnSair2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Contrato");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setName("frmCadContrato"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblContrato.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tblContrato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblContrato.setName("tblContrato"); // NOI18N
        tblContrato.setUpdateSelectionOnSort(false);
        jScrollPane2.setViewportView(tblContrato);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 540, 142));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 359, -1, 10));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contrato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Loja");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Setor");

        cboLoja.setFont(new java.awt.Font("Arial", 0, 11));
        cboLoja.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboSetor.setFont(new java.awt.Font("Arial", 0, 11));
        cboSetor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Código");

        txtCodContrato.setFont(new java.awt.Font("Arial", 0, 11));
        txtCodContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodContratoActionPerformed(evt);
            }
        });
        txtCodContrato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodContratoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboLoja, 0, 225, Short.MAX_VALUE)
                    .addComponent(txtCodContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboSetor, 0, 225, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCodContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 310, 130));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Especificações do contrato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Validade do contrato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Data Inicial");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Data Final");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Dia para Pgto.");

        txtDiaPgto.setFont(new java.awt.Font("Arial", 0, 11));
        txtDiaPgto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaPgtoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDataIni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtDataFim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDiaPgto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(txtDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(txtDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(txtDiaPgto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Parcela (R$)");

        txtVlrParcela.setFont(new java.awt.Font("Arial", 0, 11));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addComponent(txtVlrParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtVlrParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 230, 270));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Integrantes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        txtRespLoja.setFont(new java.awt.Font("Arial", 0, 11));
        txtRespLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespLojaActionPerformed(evt);
            }
        });

        txtRespShop.setFont(new java.awt.Font("Arial", 0, 11));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Responsável pelo Shopping");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Responsável pela Loja");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtRespShop, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRespLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(129, 129, 129))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRespLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRespShop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 310, 140));

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_novo.png"))); // NOI18N
        btnNovo.setToolTipText("Novo");
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoMouseClicked(evt);
            }
        });
        getContentPane().add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 11, 30, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 11, 10, 420));

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_alterar.png"))); // NOI18N
        btnAlterar.setToolTipText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarMouseClicked(evt);
            }
        });
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 46, 30, 30));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_salvar.png"))); // NOI18N
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 81, 30, 30));

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_excluir.png"))); // NOI18N
        btnExcluir.setToolTipText("Excluir");
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 116, 30, 30));

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_pesquisar.png"))); // NOI18N
        btnPesquisar.setToolTipText("Pesquisa");
        btnPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseClicked(evt);
            }
        });
        getContentPane().add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 151, 30, 30));

        btnSair2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_sair.png"))); // NOI18N
        btnSair2.setToolTipText("Sair");
        btnSair2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSair2MouseClicked(evt);
            }
        });
        btnSair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 30, 30));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-629)/2, (screenSize.height-485)/2, 629, 485);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        /*Para usar a classe de funções é necessário adicionar uma Exceção, para que se der alguma erro
         * o mesmo possa ser tratado.
         * Como não é possível alterar a linha que declara este método foi necessário inserir o função Try Catch
         */

        try {
            clsFunctions function = new clsFunctions();
            clsCadContratoDAO cadContratoDAO = new clsCadContratoDAO();

            txtCodContrato.setText(Integer.toString(function.ProxRegistro("CC_CAD_CONTRATO", "ID_CONTRATO")));

            function.carregaCombo(cadContratoDAO.ListaComboLoja(), cboLoja, "LOJA");
            function.carregaCombo(cadContratoDAO.ListaComboSetor(), cboSetor, "SETOR");

            function.carregaTabela(cadContratoDAO.ListaContrato(), tblContrato); //carrega a tabela de Contrato ao abrir tela

            clsFerramentaContrato fContrato = new clsFerramentaContrato();
            fContrato.HabilitaNovo(txtCodContrato, cboLoja, cboSetor, txtRespLoja, txtRespShop, txtDataIni, txtDataFim, txtVlrParcela, txtDiaPgto, btnAlterar, btnSalvar, btnExcluir);

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    "Ocorreram problemas ao abrir tela.\n(" + err.getMessage() + ")", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_formWindowOpened

    private void txtDiaPgtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaPgtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaPgtoActionPerformed

    private void txtRespLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespLojaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespLojaActionPerformed

    private void txtCodContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodContratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodContratoActionPerformed

    private void btnNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseClicked
        // TODO add your handling code here:

        try {
            clsFerramentaContrato fContrato = new clsFerramentaContrato();
            fContrato.HabilitaNovo(txtCodContrato, cboLoja, cboSetor, txtRespLoja, txtRespShop, txtDataIni, txtDataFim, txtVlrParcela, txtDiaPgto, btnAlterar, btnSalvar, btnExcluir);
        } catch (SQLException ex) {
            Logger.getLogger(frmCadEstacionamento.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_btnNovoMouseClicked

    private void btnAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseClicked
        // TODO add your handling code here:
        if (btnAlterar.isEnabled() != false) {
            try {
                clsFerramentaContrato fContrato = new clsFerramentaContrato();
                fContrato.HabilitaAlterar(txtCodContrato, cboLoja, cboSetor, txtRespLoja, txtRespShop, txtDataIni, txtDataFim, txtVlrParcela, txtDiaPgto, btnSalvar);
            } catch (SQLException ex) {
                Logger.getLogger(frmCadEstacionamento.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
}//GEN-LAST:event_btnAlterarMouseClicked

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_btnAlterarActionPerformed

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked

        // TODO add your handling code here:

        String sMsg = "";

        if (btnSalvar.isEnabled() != false) {
            if (txtDataIni.getDate() == null) {
                sMsg = "- Escolha uma data inicial!\n";
            }
            if (txtDataFim.getDate() == null) {
                sMsg = sMsg + "- Escolha uma data fim!\n";
            }
            if (cboLoja.getSelectedIndex() == 0) {
                sMsg = sMsg + "- Escolha a Loja!\n";
            }
            if (cboSetor.getSelectedIndex() == 0) {
                sMsg = sMsg + "- Escolha o Setor!";
            }

            if (!sMsg.equals("")) {

                JOptionPane.showMessageDialog(this,
                        "Mensagem:\n"
                        + sMsg, "Atenção!", JOptionPane.ERROR_MESSAGE);
                
            } else {

                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String sDataIni = sdf.format(txtDataIni.getDate()); // pego e transformo a data no padrão acima
                String sDataFim = sdf.format(txtDataIni.getDate()); // pego e transformo a data no padrão acima

                String sLoja, sSetor;
                int iLoja, iSetor, end;

                sLoja = (String) cboLoja.getSelectedItem();
                end = sLoja.indexOf(" ");

                if (end == -1) {
                    iLoja = Integer.parseInt(sLoja);
                } else {
                    iLoja = Integer.parseInt(sLoja.substring(0, end));
                }
                sSetor = (String) cboSetor.getSelectedItem();
                end = sSetor.indexOf(" ");

                if (end == -1) {
                    iSetor = Integer.parseInt(sSetor);
                } else {
                    iSetor = Integer.parseInt(sSetor.substring(0, end));
                }

                try {

                    clsCadContrato CadContrato = new clsCadContrato(sDataIni, sDataFim, txtRespLoja.getText(), txtRespShop.getText(),
                            Float.parseFloat(txtVlrParcela.getText()), Integer.parseInt(txtCodContrato.getText()), iLoja, iSetor, Integer.parseInt(txtDiaPgto.getText()));

                    clsCadContratoDAO CadContratoDAO = new clsCadContratoDAO();

                    CadContratoDAO.InserirContrato(CadContrato);

                    clsFerramentaContrato fChamado = new clsFerramentaContrato();
                    fChamado.HabilitaNovo(txtCodContrato, cboLoja, cboSetor, txtRespLoja, txtRespShop, txtDataIni, txtDataFim, txtDiaPgto, txtVlrParcela, btnAlterar, btnSalvar, btnExcluir);

                    clsFunctions function = new clsFunctions();
                    function.carregaTabela(CadContratoDAO.ListaContrato(), tblContrato);

                } catch (Exception err) {
                    JOptionPane.showMessageDialog(this,
                            "Não foi possível salvar/alterar este registro.\n(" + err.getMessage() + ")", "Atenção!", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
}//GEN-LAST:event_btnSalvarMouseClicked

    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
        // TODO add your handling code here:
        if (btnExcluir.isEnabled() == true) {
            try {
                clsFunctions function = new clsFunctions();
                int iContrato;

                clsCadContratoDAO CadContratoDAO = new clsCadContratoDAO();

                DefaultTableModel tableModel = (DefaultTableModel) tblContrato.getModel();

                int row = tblContrato.getSelectedRow();

                if (row != -1) {//se tiver linha selecionada, exclui da linha

                    iContrato = Integer.parseInt(tableModel.getValueAt(row, 0).toString());
                    CadContratoDAO.ExcluirContrato(iContrato);

                } else if (!txtCodContrato.getText().isEmpty()) { //senão exclui do campo
                    CadContratoDAO.ExcluirContrato(Integer.parseInt(txtCodContrato.getText()));

                } else {
                    JOptionPane.showMessageDialog(this,
                            "Selecione o dado na tabela ou digite um código a ser excluído.\n", "Atenção!", JOptionPane.ERROR_MESSAGE);
                }

                clsFerramentaContrato fContrato = new clsFerramentaContrato();
                fContrato.LimparContrato(txtCodContrato, cboLoja, cboSetor, txtRespLoja, txtRespShop, txtDataIni, txtDataFim, txtDiaPgto, txtVlrParcela);

                function.carregaTabela(CadContratoDAO.ListaContrato(), tblContrato); //atualiza a tabela de Contrato ao excluir registro

            } catch (Exception err) {
                JOptionPane.showMessageDialog(this,
                        "Não foi possível realizar Exlusão.\n(" + err.getMessage() + ")", "Atenção!", JOptionPane.ERROR_MESSAGE);
            }
        }
}//GEN-LAST:event_btnExcluirMouseClicked

    private void btnPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseClicked
        // TODO add your handling code here:
        try {

            clsFerramentaContrato fContrato = new clsFerramentaContrato();

            fContrato.LimparContrato(txtCodContrato, cboLoja, cboSetor, txtRespLoja, txtRespShop, txtDataIni, txtDataFim, txtDiaPgto, txtVlrParcela);

            fContrato.HabilitaPesquisa(txtCodContrato, cboLoja, cboSetor, txtRespLoja, txtRespShop, txtDataIni, txtDataFim, txtDiaPgto, txtVlrParcela, btnAlterar, btnSalvar, btnExcluir);

            //btnAlterar.setEnabled(true);
            //btnExcluir.setEnabled(true);

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this,
                    err.getMessage(), "Atenção!", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_btnPesquisarMouseClicked

    private void btnSair2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSair2MouseClicked
}//GEN-LAST:event_btnSair2MouseClicked

    private void btnSair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_btnSair2ActionPerformed

    private void txtCodContratoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodContratoKeyPressed
        // TODO add your handling code here:


        try {
            clsCadContratoDAO cadContratoDAO = new clsCadContratoDAO();
            clsFerramentaContrato fContrato = new clsFerramentaContrato();

            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

                ResultSet rst = cadContratoDAO.ConsultarContrato(Integer.parseInt(txtCodContrato.getText()));
                if (rst.next()) {

                    cboLoja.setSelectedItem(rst.getString("LOJA"));
                    cboSetor.setSelectedItem(rst.getString("SETOR"));
                    txtRespLoja.setText(rst.getString("RESP_LOJA"));
                    txtRespShop.setText(rst.getString("RESP_SHOP"));
                    txtDataIni.setDate(rst.getDate("DATA_INICIO"));
                    txtDataFim.setDate(rst.getDate("DATA_FIM"));
                    txtDiaPgto.setText(rst.getString("DATA_MENSAL"));
                    txtVlrParcela.setText(rst.getString("VLR_PARCELA"));

                    btnAlterar.setEnabled(true);

                } else {
                    JOptionPane.showMessageDialog(this,
                            "Contrato não cadastrado.\n", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
                    fContrato.LimparContrato(txtCodContrato, cboLoja, cboSetor, txtRespLoja, txtRespShop, txtDataIni, txtDataFim, txtDiaPgto, txtVlrParcela);
                    btnAlterar.setEnabled(false);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Não foi possível encontrar o contrato.\n", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtCodContratoKeyPressed
    /**
     * @param args the command line arguments
     */
    void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmCadContrato().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair2;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cboLoja;
    private javax.swing.JComboBox cboSetor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.ButtonGroup optStatus;
    private javax.swing.JTable tblContrato;
    private javax.swing.JTextField txtCodContrato;
    private com.toedter.calendar.JDateChooser txtDataFim;
    private com.toedter.calendar.JDateChooser txtDataIni;
    private javax.swing.JTextField txtDiaPgto;
    private javax.swing.JTextField txtRespLoja;
    private javax.swing.JTextField txtRespShop;
    private javax.swing.JTextField txtVlrParcela;
    // End of variables declaration//GEN-END:variables
}
