SELECT (IFNULL(A.QTD,0) - IFNULL(B.QTD,0)) ESTOQUE,
       A.MES,
       B.MES,
       A.PRODUTO,
       B.PRODUTO,
       A.QTD,
       B.QTD
  FROM 
-- entrada
(SELECT DATE_FORMAT(ENT.DATA_CAD,'%m') MES,
       PROD.DESC_PROD PRODUTO,
       SUM(ENT.QTD_ENTRADA) QTD,
       PROD.ID_PRODUTO
  FROM CC_CAD_ENTRADA ENT,
       CC_CAD_PRODUTO PROD
 WHERE PROD.ID_PRODUTO = ENT.ID_PROD
 GROUP BY DATE_FORMAT(DATA_CAD,'%m'),
          PROD.DESC_PROD
 ORDER BY PROD.DESC_PROD ) A
 
    LEFT JOIN
 -- consumido
 (SELECT DATE_FORMAT(CONS.DATA_CAD,'%m') MES,
       PROD.DESC_PROD PRODUTO,
       SUM(CONS.QTD_CONSUMO) QTD,
       PROD.ID_PRODUTO
  FROM CC_CAD_CONSUMO CONS,
       CC_CAD_PRODUTO PROD
 WHERE PROD.ID_PRODUTO = CONS.ID_PROD
 GROUP BY DATE_FORMAT(DATA_CAD,'%m'),
          PROD.DESC_PROD
 ORDER BY PROD.DESC_PROD ) B
 
 ON A.ID_PRODUTO = B.ID_PRODUTO
 AND A.MES = B.MES

