SELECT DATE_FORMAT(DATA_INICIO,'%m') MES_INI,
       DATE_FORMAT(DATA_FIM,'%m') MES_FIM,
       DATE_FORMAT(DATA_INICIO,'%Y') ANO_INI,
       DATE_FORMAT(DATA_FIM,'%Y') ANO_FIM,
       VLR_PARCELA
  FROM CC_CAD_CONTRATO
 WHERE DATE_FORMAT(SYSDATE(),'%d/%m/%Y') <= DATE_FORMAT(DATA_FIM,'%d/%m/%Y') -- não considera contrato vencidos
ORDER BY DATA_INICIO