SELECT LOJA.NOME_FANTASIA,
       SETOR.DESC_LOCAL
  FROM CC_CAD_CONTRATO CONTRATO,
       CC_CAD_LOJA LOJA,
       CC_CAD_SETOR SETOR
 WHERE CONTRATO.ID_LOJA = LOJA.ID_LOJA
   AND CONTRATO.ID_SETOR = SETOR.ID_SETOR